### ISSUE TITLE
Can not connect to SSID with spaces

### ISSUE THREAD

**Issue by burkadius** [s60sc/ESP32-CAM_MJPEG2SD#10]
Hello s60sc, first of all thank you very much for publishing your program code, it is exactly what I was looking for, I especially like the possibility to delete files on the SD card. Unfortunately I am not a programmer and have only very limited knowledge.  But anyway, the installation of the code is successful and I can connect to the camera in AP mode. But if I enter my SSID either in the code (myConfig) or under 192.168.4.1 there is no connection to the router. I get in the monitor of the IDE the info "connectet to 0.0.0.0 . Then I found out that it works without spaces in my SSID.
Can you give me a hint what I am doing wrong.
Best regards
Burkhard

**Comment by s60sc** [comment]
Thanks
How long is your ssid, if longer than 20 chars then increase ST_SSID[20]

**Comment by burkadius** [comment]
Yes, You are right, my SSID is 22 chars long and also my pass (21 char). But there are no better results after changing to 23 char for both

**Comment by s60sc** [comment]
@gemi254 who contributed this code may be able to help

**Comment by burkadius** [comment]
ok, thanks for this link, I will ask gemi.

**Comment by gemi254** [comment]
> Hello s60sc, first of all thank you very much for publishing your program code, it is exactly what I was looking for, I especially like the possibility to delete files on the SD card. Unfortunately I am not a programmer and have only very limited knowledge. But anyway, the installation of the code is successful and I can connect to the camera in AP mode. But if I enter my SSID either in the code (myConfig) or under 192.168.4.1 there is no connection to the router. I get in the monitor of the IDE the info "connectet to 0.0.0.0 . Then I found out that it works without spaces in my SSID.
> Can you give me a hint what I am doing wrong.
> Best regards
> Burkhard

Spaces not handled correctly without url encode url. Also ssid field size was too small.
Laters version 
https://github.com/gemi254/ESP32-CAM_MJPEG2SD
has fixed the problem using url encoded requests so it will work correctlly…
If you wish compile with 
Tools->Core Debug level -> Verbose 
and check serial monitor..

**Comment by drmartin1234** [comment]
I agree with Burkhard, excellent software.  However, I think I have a follow on issue.  My SSID has a period i.e. a "." at the end.  The cam will not log on to the router.  I have many cams that log on to the Espressif supplied web server with no problems.  I also have many other ESPs doing MQTT with no problem logging on.  I get the same, "I get in the monitor of the IDE the info "connectet to 0.0.0.0 ." after it fails.  What do you think?  I can get rid of the "." its just going to be a pain reflashing all those ESPs.  But your software is worth it.  Thank you!

**Comment by s60sc** [comment]
I implemented a fix that should address this but didnt upload it as I was working on further changes that I haven't got round to finishing.  I've  uploaded the fix now.

**Comment by gemi254** [comment]
Some special chars lkie dot not handled correctly in encoded url function.
Laterst version
https://github.com/gemi254/ESP32-CAM_MJPEG2SD
Fix this

**Comment by s60sc** [comment]
Uploaded a fix for dots. Will subsequently make function generic when do merge
