### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by C4PT41ND34DP00L** [s60sc/ESP32-CAM_MJPEG2SD#100]
It would be awesome if we could use the OTA to update the HTML and other data files.

**Comment by C4PT41ND34DP00L** [comment]
Does that update the HTML and other files in the data folder?

**Comment by C4PT41ND34DP00L** [comment]
Can you explain how? I know how to update the code via OTA but I have no idea how to update the files in data is it all in one?

**Comment by s60sc** [comment]
just select required file and upload it

**Comment by C4PT41ND34DP00L** [comment]
I was unaware of this thank you.
