### ISSUE TITLE
Feature request: save x seconds before motion triggered

### ISSUE THREAD

**Issue by RibeiroSantos** [s60sc/ESP32-CAM_MJPEG2SD#101]
Hi,
When there are fast movements, the movement triggers and, by the time the cam starts recording, the movements may have already passed. This is perhaps more frequent in situations with less light. Is it possible, in the recording file, to also have the record of a few moments before the movement was triggered? That is, recording starts x seconds before motion is detected.
Thanks and congrats by excellent work.

**Comment by s60sc** [comment]
Would need a large cyclic buffer in PSRAM. Not feasible with ESP32. May be feasible if/when ESP32-S3 camera modules are available
