### ISSUE TITLE
Cannot get the interface to work and there is no stream.

### ISSUE THREAD

**Issue by martinmutter** [s60sc/ESP32-CAM_MJPEG2SD#103]
It streams but only when I do 192.168.x.xxx:81/Stream

Files on SD card and serial monitor also confirms it works.

But nothing happens when I press anything on the interface. The buttons flash green and then turns red again. And the serial monitor doesn't indicate anything happening. The only time it does anything in monitor is when I cover the camera and causes it to go into nightmode (which is how I found out the camera even worked). 

Reinstalled it from scratch 10 times. The example ESP32 cam works great. But lacks all the nice features yours has so reallyreally want to get this working.

The only things I have changed/added is SSID and wifi password. That's it.

I have  no idea what I'm doing wrong here. Followed the guide [Max Imagination](https://www.instructables.com/member/Max+Imagination/)

Could it be an knockoff brand ESP32? Would that affect the webservers ability to communicate with the Camera?

![Screenshot 2022-06-11 043953](https://user-images.githubusercontent.com/47459850/173169527-e8777b9c-e103-4e8c-8158-0b2a826cf5dd.jpg)
![Screenshot 2022-06-11 043617](https://user-images.githubusercontent.com/47459850/173169440-ac6de703-1a74-4602-a38d-f823a4b79e9c.jpg)
![Screenshot 2022-06-11 043710](https://user-images.githubusercontent.com/47459850/173169441-7dd0feb0-1979-4d52-8f30-c56102b6189a.jpg)

**Comment by s60sc** [comment]
No idea, but not a hardware problem.
Try a different browser.
In Chrome or Edge press Ctrl-Shift-I (letter i) together to bring up inspection screen and see what's logged when you interact with the page

**Comment by martinmutter** [comment]
This is what I can find when inspecting. I am not sure what you want me to look for but this is what I found relating to the stream button and the only thing the console seemed to care about.

Not a programmer (beyond copying and pasting until it "works" together) so I am not sure what I need or can provide you with to maybe help me with this. Using Brave (PC and Android) and have tried in chrome and edge as well. Will continue trying in a bunch of other browsers. 

![Screenshot 2022-06-12 232328](https://user-images.githubusercontent.com/47459850/173254236-4823a78f-9351-4283-964e-87cb931f4e72.jpg)
![Desktop Screenshot 2022 06 12 - 23 17 32 28 (2)](https://user-images.githubusercontent.com/47459850/173254241-56a75515-42bc-4fdd-a1bd-97720b7237a8.png)

**Comment by martinmutter** [comment]
Firefox threw me this

![Screenshot 2022-06-12 234903](https://user-images.githubusercontent.com/47459850/173255084-5d1e6d20-2849-403a-9a85-8c6b63f3b23e.jpg)

**Comment by s60sc** [comment]
The page doesnt work because of the error. Do you have a valid jquery.min.js in the data folder on your sd card? Try loading a fresh copy from the repository.

**Comment by martinmutter** [comment]
Well took a look and yea. The script was 0kb. So directly pasted the one from the zip. But didn't change anything. Might have to look into a different way to install? 

Currently launching the .ino in the folder with -master removed. Adding wifi stuff. Then upload. Without the SD in. (since the guide said it should be put in after installing)

Could the issue be the 32gb sd card? It's a Sandisk Extreme HC I. So it's a rather good SD card but I know some things have issues with the HC cards.... Just spitballing longshots here.

**Comment by nnjim** [comment]
Note that Expressif state the esp32-cam officially supports a maximum size of 4GB microSD card. Many have got larger sizes to work, but I've only managed to get a max of 16GB to work. Note also that it must be formatted in fat32 format.

**Comment by s60sc** [comment]
I've used 32gb card ok. The problem is related to your installation, which I cant help further with.

**Comment by martinmutter** [comment]
Well just gonna have to reinstall untill it works I guess. It might be an offbrand ESP32 CAM module. So might have to figure out which board I have to pick for installation....
