### ISSUE TITLE
Timelapse feature

### ISSUE THREAD

**Issue by YapCK45** [s60sc/ESP32-CAM_MJPEG2SD#104]
I tried using the time lapse feature. I turned on time lapse and save capture in the interface and started recording. The video is recorded but there is no file with the _T suffix. Also how are the time lapse parameters set?

On this note, I don't see a function for recording ad hoc stills. I reckoned this would be subsumed until time lapse.

Kudos for the stupendous project. Great job! Learnt a lot from it. It's been a lot of fun since I managed to get it working. Noticed that there is a pan-tilt function. Can't wait to get that to work with the servos.

**Comment by s60sc** [comment]
timelapse file not created  until end of timelapse duration - see myconfig.h

**Comment by YapCK45** [comment]
Thanks. Checked it out and changed the parameters for a shorter duration and it works!
