### ISSUE TITLE
Error msg: File does not exist or cannot be opened

### ISSUE THREAD

**Issue by duceduc** [s60sc/ESP32-CAM_MJPEG2SD#106]
I have successfully setup the esp32 cam. I can view from a browser, but I get this error in browser after several hours later.
```
File does not exist or cannot be opened
```

I can ping the device, just cannot access it via the browser any longer without a reboot of device. Running V6.2

**Comment by s60sc** [comment]
the web server is running, and telling you  there is a problem with the requested file
