### ISSUE TITLE
FTP upload speed

### ISSUE THREAD

**Issue by FKW9** [s60sc/ESP32-CAM_MJPEG2SD#111]
Any way to increase upload speed? It takes about 355secs for 40MB..
Increasing the CHUNKSIZE doesn't affect the speed.

My WiFi connection is very good with about -26dBm and the FTP server works also very well (less than 1sec for 40MB from my desktop-pc), so the bottleneck is definitely on the ESP.

Thanks

**Comment by s60sc** [comment]
Cant expect desktop pc performance from a tiny MCU

**Comment by FKW9** [comment]
... i'll figure it out myself.
