### ISSUE TITLE
Timelapse triggered a reboot

### ISSUE THREAD

**Issue by YapCK45** [s60sc/ESP32-CAM_MJPEG2SD#113]
Tried out the time lapse using:
a. Time lapse duration = 30 minutes
b. Time lapse playback FPS = 1
c. Time lapse interval (secs) = 15

This should capture 120 frames. The serial monitor on the development kit shows that when the time lapse button was clicked, it triggered a reboot. Screen shot below:

![image](https://user-images.githubusercontent.com/64215797/182023895-82124418-3cf0-4d1e-90fc-b354128a7659.png)

Is there something I did that is incorrect? No problem with time lapse on v6.2.3 using the same setup.

**Comment by s60sc** [comment]
might be insufficient ram, I'll investigate

**Comment by YapCK45** [comment]
I think that is probably correct. 
I disabled motion detect and it worked without triggering the reboot. 
Apparently some other events also be triggering that and sometimes the serial monitor stopped capturing. I had to restart another instance for it to capture properly.
Saw something about IO Extender not used when the system booted up and peripherals being hosted on separate ESP in the update documentation. Not sure what that is about.

**Comment by s60sc** [comment]
updated to reduce ram usage

**Comment by YapCK45** [comment]
Version 7.2 does not seem to work. Enabling time lapse still triggering a reboot. Double checked it on 2 ESP32-Cam modules and also using lower resolution.
Please confirm that the partition scheme to use.

**Comment by YapCK45** [comment]
Done some more testing. Seems like Enable Motion Detect and Save Capture can be dependent on the hardware. Checked on 2 ESP32-Cam with the came code (v7.2). One work without problem while the other would trigger a reboot when motion is detected. Information captured on serial monitor:
![image](https://user-images.githubusercontent.com/64215797/184473924-3c593cd2-6d5b-47b8-8b9a-725e7ac30813.png)


Any suggestion how to mitigate this issue?
