### ISSUE TITLE
SSID and WIFI-Password - where to enter ?

### ISSUE THREAD

**Issue by Aquillum** [s60sc/ESP32-CAM_MJPEG2SD#114]
I compiled it and saved the /data Folder to the SD Card.
I can connect to the AP and wanted to enter my WIFI SSD and PW.
Where do I enter the SSID and WIFI password ? 
Can I do it directlty in the config.txt (  Icant find a SSID_PW there) ? I also don't find the SSID/PW in the WIFI Web Config.

Please give a small example where and what to enter. Thank you !

**Comment by s60sc** [comment]
Main web page under Other Settings

**Comment by Aquillum** [comment]
OK ! 
I searched in _Edit Config --> Wifi and Other_
Got it now !
Thank you !
