### ISSUE TITLE
Update configuration after playing from SD card

### ISSUE THREAD

**Issue by YapCK45** [s60sc/ESP32-CAM_MJPEG2SD#116]
Two requests:
Request 1:
The **Start Stream** button is used to play the captured video on the SD card after the file had been selected and the button would show **Stop Stream.** 
Request that the status be reset to **Start Stream** after the video had completed streaming. This would prepare the system to stream another video. Otherwise the user need to click Stop Stream (which had already ended) before he could playing the selected file again or starting another selected file.

Request 2:
The **Select File/Folder** drop down reverts back to ** -Select- ** after a folder/file saved on SD card had been deleted.
Request that it remains in the selected option to facilitate deletion of other folder/file. This would be more functional as there is a **-Up** option in the dropdown to move up for folder selection.

**Comment by s60sc** [comment]
UI improvements added
