### ISSUE TITLE
Motion Detection and Save Capture is hardware dependent

### ISSUE THREAD

**Issue by YapCK45** [s60sc/ESP32-CAM_MJPEG2SD#117]
Tested the Motion Detect and Save Capture function. Seems like they could be dependent on the hardware. Checked on 2 ESP32-Cams with the came code (v7.2). One works without problem while the other would trigger a reboot when motion is detected. Information from serial montior:

![image](https://user-images.githubusercontent.com/64215797/184476677-8f4307de-9bed-4c78-93e8-e0d8a070a544.png)

Motion will consistently trigger a reboot. I did not realize this until I saw it on the serial monitor when checking another problem. Probably won't notice this at all and would be wondering why there is no capture. Any idea what is causing it and how to mitigate this issue?

It is interesting to note that this unit would reboot if the **record button** (forced recording) is pressed.
I don't have a PIR sensor but I reckon it would also cause a reboot.

**Comment by s60sc** [comment]
You need to decode the stack trace: https://github.com/me-no-dev/EspExceptionDecoder

**Comment by YapCK45** [comment]
Tested the Motion Detect and Save Capture function. Seems like they could be dependent on the hardware. Checked on 2 ESP32-Cams with the came code (v7.2). ~~One works without problem while the other would trigger a reboot when motion is detected. Information from serial montior:~~ Rechecked again and it seems both have the same problem. So it is unlikely to be the hardware. Checked the same hardware with v6.2.3 and have the same problem. The puzzling part is that I have one unit running v6.2.3 for days without problem.
Decoding the stack trace is another level of complexity. Not sure I want to go there

**Comment by YapCK45** [comment]
I think you can close this.
