### ISSUE TITLE
System reboots when resolution set to higher than SVGA in v7.2

### ISSUE THREAD

**Issue by YapCK45** [s60sc/ESP32-CAM_MJPEG2SD#120]
System reboots when resolution set to higher than SVGA

When resolution is set to higher than SVGA, v7.2 reboots and resets to default SVGA resolution. 

Had been using v6.3.2 and therefore revert to this version with similar result. However, if **Clear NVS** is done before reverting to v6.3.2, then it works as before. Seems like it has something to do with the NVS as I observed the Serial monitor shows:
'Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled' when this happens.

Duplicated this on another ESPCam32 module with identical results.

The above issue does not happen if Motion detection and Save capture are not enabled.

**Comment by s60sc** [comment]
NVS only used for passwords
