### ISSUE TITLE
can i add the esp32-cammjpeg2sd ip camera viewer 4?

### ISSUE THREAD

**Issue by ryzencraft** [s60sc/ESP32-CAM_MJPEG2SD#121]
can i add the esp32-cammjpeg2sd ip camera viewer 4?

**Comment by s60sc** [comment]
not understood

**Comment by ryzencraft** [comment]
i mean if i can stream only live video to somethink like a vlc or ip camera viwer app

**Comment by s60sc** [comment]
http://<ip address>:81/stream. 
if viewer  can decode mjpeg stream

**Comment by ryzencraft** [comment]
![image](https://user-images.githubusercontent.com/95238289/186417133-f584a810-c98f-46bc-82de-6347e1521d9b.png)
omg it worked thanks a lot for your help
