### ISSUE TITLE
Bluetooth connection instead of wifi

### ISSUE THREAD

**Issue by eadmaster** [s60sc/ESP32-CAM_MJPEG2SD#128]
can we use BT instead of wifi for remote connection?

Should provide lower battery usage and may be easier to use in some situations.

It may still use a web browser for user interaction thanks the new WebBluetooth API (see https://github.com/hewittwill/WebBluetooth-Terminal)

**Comment by s60sc** [comment]
I've never used the BT stack, but someone else is welcome to try
