### ISSUE TITLE
stream with CIF and record with VGA

### ISSUE THREAD

**Issue by monroed11** [s60sc/ESP32-CAM_MJPEG2SD#129]
Hi,

Is it possible to stream with CIF and record to SDcard with VGA? or Stream with VGA: FPS=1 and record with 10FPS? it seems that streaming with 1 FPS is smoother than putting it in 10.

**Comment by s60sc** [comment]
camera only has one frame rate/size so you would have to do it in software

**Comment by monroed11** [comment]
Any key pointers on how to do it? I am quite new on esp32 so I have no idea how to start
