### ISSUE TITLE
Playback and resolutions higher than SVGA not working in ver 7.4

### ISSUE THREAD

**Issue by YapCK45** [s60sc/ESP32-CAM_MJPEG2SD#132]
The new GUI is quite nice. But there are two problems. Don't think it is a hardware problem as sketch was updated from v7.3 to v7.4 using the corresponding /data folder. Also checked it on another ESPCAM32 module with identical results:

**The playback button causes a reboot**
After the avi file is selected, clicking Start Playback triggers a reboot. This is detected if the ESPCAM32 is connected to the serial monitor.
![image](https://user-images.githubusercontent.com/64215797/192315851-5d6ed1d1-9893-47c3-876c-f573e3e796de.png)

**Changing resolution from SVGA(800x600) to higher resolution**
Resolution is set to SVGA(800x600) on power up. Setting the resolution to anything higher triggers a reboot and core dump. Again captured on serial monitor.
![image](https://user-images.githubusercontent.com/64215797/192315391-2634899d-810d-47dd-a3f2-a71514a45ee2.png)

**Changing resolution from SVGA(800x600) to lower resolution**
Changing to lower resolution serial monitor trace
![image](https://user-images.githubusercontent.com/64215797/192319107-3867ab1a-4ee5-49b9-9ef0-2f6876b0664d.png)

**Comment by s60sc** [comment]
Cant get above issues to occur and v7.4 was only UI changes. Increased task sizes in case but unlikely to be issue. Wdt timeout indicates somethhing is causing the esp to hang, but without decoded stack traces I cannot investigate further.

**Comment by YapCK45** [comment]
I can find out how to decode the stack traces and post them. Don't want to take up too much of your time.
Noticed that the wdt timeout were not CPU0 and CPU1 although the compilation selected **CPU1** only for event and arduino. Would it make any if both were selected?

**Comment by s60sc** [comment]
Installing and using decoder is straightforward - [see here](https://github.com/me-no-dev/EspExceptionDecoder)

**Comment by YapCK45** [comment]
I have installed the ESP Exception Decoder tool and captured the stack traces. It turns out there are two traces - one for CPU 0 and one for CPU 1 - for each of the issues.

**Exception due to playback**
CPU 0
![image](https://user-images.githubusercontent.com/64215797/192764361-e9191fb0-2980-47c4-a224-aa054bf63d51.png)
CPU 1
![image](https://user-images.githubusercontent.com/64215797/192765775-b36d75ea-3877-49e9-aeb8-dfd0be195885.png)

**Exception due to changing of resolution**
CPU 0
![image](https://user-images.githubusercontent.com/64215797/192764582-7c831912-cc83-43f2-8588-6a1dc631ffc2.png)
CPU 1
![image](https://user-images.githubusercontent.com/64215797/192764648-804537b0-9b97-46ce-98b7-34f0b4468326.png)

I repeated the tests and the traces are the same and repeatable. I am not able to make any sense out of these traces but it seems like one of them triggered the other. Code was compiled using the default with CPU 1.
![image](https://user-images.githubusercontent.com/64215797/192766610-e766baed-d3a7-4973-acbf-59297bcdb03a.png)

Your comments please.

**Comment by s60sc** [comment]
Core 1 crashing due to ISR hanging.  The only app ISR is frameISR() - have you modified it? 
Core 0 crash does not trace to the app (as expected) but to freertos and no guru meditation reason is given. 
It is strange for both cores to crash and with very little decoding info so could indicate a hardware problem. do you have peripherals connected or made hardware mods.

**Comment by YapCK45** [comment]
Unlikely to be due to hardware problem. Have tested with different ESP32 Cam modules with similar result. The same hardware also worked well using earlier versions eg v6.2.3 and v7.3. 
No modification of ISR. Using the code Out of Box.
I do have pan tilt servos connected to the GPIOs but have not activated them. The web interface is very handy. The Pan Tilt work quite well in v7.3 although have not stress tested them. No other peripheral.

**Comment by s60sc** [comment]
try disconnecting the servos from the gpio pins

**Comment by YapCK45** [comment]
The servos are not connected to the ESP32 Cam during troubleshooting. Totally floated and disconnected. The ESP32 Cam is only connected to the com port for the serial monitor.

**Comment by s60sc** [comment]
As I cant recreate the problem and no one else has reported it, I cant do any further diagnosis

**Comment by YapCK45** [comment]
I looked at the code for frameISR() after your comment. Noticed that line 95 in mpeg2sd.cpp is:

timer3 = timerBegin(3, 8000, true); // 0.1ms tick

This assumes that the CPU frequency is 80MHz. It won't be 0.1ms tick if the clock is 240MHz. How would this affect the interrupt frequency?

**Comment by s60sc** [comment]
[The timer uses the APB_CLK clock source (typically 80 MHz),](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/system_time.html)
The hanging ISR is a freertos ISR
