### ISSUE TITLE
Using sd cards with capacities higher than 4GB

### ISSUE THREAD

**Issue by YapCK45** [s60sc/ESP32-CAM_MJPEG2SD#133]
It is almost impossible to get 4GB sd cards nowadays. The minimum is 16GB. According to the ESP32Cam specs by espressif, 4GB is officially supported although I have been able to use 16GB without problem so far.

The current code in utilsSD.cpp deletes the oldest dir when the disk is full. 
It would be good if it can support multiple partitions. It is quite easy to format the higher capacity sd cards with multiple partitions.  When one is full, move to the next partition and override the oldest folder in the first partition when the last partition is full.

Related to this, not all the logs written to the serial monitor is captured by the logs to sd card. It would be helpful for troubleshooting.

**Comment by s60sc** [comment]
32gb sd work ok.  Someone else is welcome to write code for multiple partitions.

**Comment by monroed11** [comment]
Just use Minitool Partition Wizard and format the SD card to Fat32. I am using 64GB and so far its working. No code modified.
