### ISSUE TITLE
Cannot find v7.4

### ISSUE THREAD

**Issue by YapCK45** [s60sc/ESP32-CAM_MJPEG2SD#134]
Cannot find v7.4 anymore. Was able to access it a couple of weeks back but was not able to get it to work. Now can only find v7.3.1

Have been testing v7.3.1. Here are some observations and questions:

1. Earlier versions (eg v6.2.3) that work may not work when upgraded (eg v7.3) using the same hardware, 
2. Same code (eg 7.3.1) may not work on another ESP32 module. Not sure why.
3. Understand that the ESP32 code is running on freertos. How is it installed and updated?

**Comment by s60sc** [comment]
Its here on github
