### ISSUE TITLE
problem with sending email

### ISSUE THREAD

**Issue by maxbrax** [s60sc/ESP32-CAM_MJPEG2SD#135]
Hello
I am very happy with this project, everything works fine, only one problem with sending the email when activating a movement, the emeil is not sent and I get the following error message "`[15:29:12.035 ERROR @ smtp.cpp:67] Command HELO ESP-CAM_MJPEG: got wrong response: HELO requires valid address`",
yet I enter all the data correctly in the SMTP settings.
How can I solve this?.
Thank you in advance for your help
Maximum

**Comment by s60sc** [comment]
I've never seen that error

**Comment by bassamjarad** [comment]
smtp.cpp => sprintf(content, "MAIL FROM: <%s>", APP_NAME);
uses the app name as the sender email which is invalid email address.

I've modified this by replacing APP_NAME with my email like this:
sprintf(content, "MAIL FROM: <%s>", "test@gmail.com");

then, it worked for me. 

I hope this helps.

**Comment by maxbrax** [comment]
thanks for the tip , i will try it
