### ISSUE TITLE
Webpage Controls not working and no live stream 

### ISSUE THREAD

**Issue by Harshil6** [s60sc/ESP32-CAM_MJPEG2SD#136]
I have succesfully uploaded the code on the board, following all instructions listed in installation. I am not getting any live stream on the web page and the buttons are unresponsive to commands. Only motion detection is triggering the recording and I can't access the recording on the sd card. 

Please help!

**Comment by s60sc** [comment]
Check your browser console for errors. Did you copy jquery_min.js to the /data folder
