### ISSUE TITLE
Timezone imposible to change

### ISSUE THREAD

**Issue by Potracheno** [s60sc/ESP32-CAM_MJPEG2SD#150]
Ver. 8.0

Any timezone I choose and always get the same UTC +0. 
I found a bug in [MJPEG2SD.htm](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/blob/master/data/MJPEG2SD.htm#L1176)
Seems should be **option value="Etc/**GMT+1**">GMT+1:00** and so on. I've tried to edit this that way but failed. Also I've tried to insert values like **EET-2EEST,M3.5.0/3,M10.5.0/4** but still no luck. Must be problem is somewhere deeper in a code. In a log I see massage that time synchronized  with NTP server correctly.

**Comment by s60sc** [comment]
There is a problem now with the Etc/GMT codes not being recognised, I'll investigate

**Comment by s60sc** [comment]
Should be fixed with 2 new files

EET-2EEST,M3.5.0/3,M10.5.0/4 can be used by pasting it directly into Time Zone field

**Comment by dsfifty** [comment]
I can't get my time zone to work. I've updated the two files.
ACST-9:30ACDT-10:30,M10.5.0/02:00:00,M4.1.0/03:00:00 (pasted directly into the time zone field)
Not even +10 will save.

**Comment by s60sc** [comment]
Unfortunately that particular time string contains a colon which conflicts with a delimiter I use that then corrupts the time zone value until the configs.txt file is replaced. I'll look at a fix

**Comment by s60sc** [comment]
Fixed in 8.1

**Comment by dsfifty** [comment]
Thanks for your fast response. I can confirm that time zone
ACST-9:30ACDT-10:30,M10.5.0/02:00:00,M4.1.0/03:00:00
works well now.

Thanks for your efforts in this very useful project.

**Comment by Potracheno** [comment]
Works

**Comment by s60sc** [comment]
should be fixed in v8.3.2
