### ISSUE TITLE
Add a configuration option to set the NTP server

### ISSUE THREAD

**Issue by KamalW** [s60sc/ESP32-CAM_MJPEG2SD#151]
I have a device within an access controlled environment that fails to contact the hard coded NTP server.

To let a custom NTP server be specified, please add a configuration option.

**Comment by Potracheno** [comment]
You can do it by yourself now it hardcoded [here](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/blob/master/utils.cpp#L250)
Just change **pool.ntp.org** to anything you like.

**Comment by s60sc** [comment]
will add as I've got to do a fix anyway

**Comment by s60sc** [comment]
Version 8.2

**Comment by KamalW** [comment]
Thank you. It's working well.

**Comment by KamalW** [comment]
Closing since the requested feature was added.
