### ISSUE TITLE
download Files faster.

### ISSUE THREAD

**Issue by monroed11** [s60sc/ESP32-CAM_MJPEG2SD#157]
Hi, 
I am not sure if this is only happening to me. When downloading footages, it takes quite some time. I am only seeing 200 - 250 kbps when downloading a footage of any size, sometimes it drops to 20 - 50 kbps. Please let me know your thoughts about this.

**Comment by chunter1** [comment]
Ahmmm...  it's 2 meters away from the AP and at about -50dBm RSSI.
