### ISSUE TITLE
Access settings are not or only randomly loaded

### ISSUE THREAD

**Issue by chunter1** [s60sc/ESP32-CAM_MJPEG2SD#158]
When i change settings in the "access settings" menue and reboot the device, the settings are not shown after reboot finished.
Tried to reload the website and using firefox/chrome - still not working.
SD-card is a 8GB one but changing it also made no difference.

**Comment by s60sc** [comment]
press the save button

**Comment by chunter1** [comment]
Ofcourse i did press the save button before rebooting.

**Comment by s60sc** [comment]
type http://<ip>/web?configs.txt and see if the file has changed

**Comment by s60sc** [comment]
github auto corrected, should say "http://[ip]web?configs.txt"

**Comment by s60sc** [comment]
github auto corrected again, should say "http://[ip]/web?configs.txt"

**Comment by chunter1** [comment]
I guess we got a misunderstanding here.
It's not that the settings are ignored... they are simply not displayed on the webpage - no matter how often i press the browser reload button.
They only appear randomly.

![settings_not_showing](https://user-images.githubusercontent.com/16907942/215274690-bea09127-b677-4a90-a81f-ebea47c0c3b3.jpg)

**Comment by s60sc** [comment]
implies a connection problem, open your browser inspector ctrl-shift-i to see what the network is doing

**Comment by chunter1** [comment]
It's not a network issue since the other pages are working correctly.
