### ISSUE TITLE
It never comes back to STA mode once becomes AP mode. 

### ISSUE THREAD

**Issue by CazYokoyama** [s60sc/ESP32-CAM_MJPEG2SD#162]
My came locates far from WiFi router and disconnects from time to time. Once it becomes AP mode, it never comes back to STA mode.
I'd rather prefer it reboots on AP mode every 10 min or so. If you give me a hint where I should look at, I'll create a patch.
I tested on 7.4. Disregard and close If this problem does not exist on 8.4.

**Comment by s60sc** [comment]
In v8, AP and STA are availlable simultaneously. so STA will retry every 30 secs by default - can be changed
