### ISSUE TITLE
 OTA update fails at 4% on every 20 attempts

### ISSUE THREAD

**Issue by CazYokoyama** [s60sc/ESP32-CAM_MJPEG2SD#163]
Uploading fails at 4% every 20 attempts. I tested on 7.4. Does OTA update work? 
How you load a new binary? by OTA? through USB adapter?

**Comment by s60sc** [comment]
OTA will fail if the wifi conn is poor.  Alternatively use arduino ide / usb

**Comment by CazYokoyama** [comment]
I tested by moving AI-thinker closer to router such as 1 meter. Still have the symptom.

**Comment by s60sc** [comment]
bin should work as well
