### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by Ihor59** [s60sc/ESP32-CAM_MJPEG2SD#165]
Configuration file is impossible to edit directly (without Wi-Fi)  with MJPEG2SD.HTML

**Comment by s60sc** [comment]
github autocorrected it
key-value-group-type-label
where - represents the tilde delimiter

**Comment by Ihor59** [comment]
It should be more convenient to have an easier way to edit this file. Not everywhere, Wi-Fi and Internet is present. 

It just suggestion

**Comment by Ihor59** [comment]
Thank you, Now I understand how it works
