### ISSUE TITLE
OTA Upload fails -abort() was called at PC 0x400827a2 on core 1

### ISSUE THREAD

**Issue by AlanTwigg** [s60sc/ESP32-CAM_MJPEG2SD#168]
Hi, trying to use the OTA Update facility, I export the compiled binary of my sketch and choose this file in the OTA Update facility.
Arduino IDE serial monitor reports the following:-[16:03:21.996 OTAtask] Starting OTA server on port: 82
16:03:21.995 -> [16:03:22.110 uploadHandler] Partition update using file ESP32-CAM_MJPEG2SD-V2.ino.esp32.bin
16:03:21.995 -> 
16:03:21.995 -> abort() was called at PC 0x400827a2 on core 1
16:03:21.995 -> 
16:03:21.995 -> 
16:03:21.995 -> Backtrace: 0x40083edd:0x3ffb2020 0x40090b69:0x3ffb2040 0x400972c5:0x3ffb2060 0x400827a2:0x3ffb20e0 0x400fcf13:0x3ffb2130 0x400f071d:0x3ffb2150 0x400e7137:0x3ffb2170 0x400e72d1:0x3ffb2190 0x400e5899:0x3ffb21c0 0x401c8fa5:0x3ffb2230 0x400ea056....................more

Arduino IDE is 1.8.20, ESP32 is 2.0.6
Wifi is excellent as I'm uploading ftp files from the CAM module to a local server.
Board is AI Thinker ESP32 -CAM, partition scheme is Huge APP ( 3Mb No OTA/1MB SPIFFS)

**Comment by s60sc** [comment]
You cant use OTA with a non-OTA partition scheme - Huge APP ( 3Mb No OTA/1MB SPIFFS).

**Comment by AlanTwigg** [comment]
Hi thank you for responding so quickly, yes I should have spotted that. Great software does everything I need.
Thankyou
Alan

From: s60sc ***@***.***>
Date: Tuesday, 7 February 2023 at 22:05
To: s60sc/ESP32-CAM_MJPEG2SD ***@***.***>
Cc: alan twigg ***@***.***>, Author ***@***.***>
Subject: Re: [s60sc/ESP32-CAM_MJPEG2SD] OTA Upload fails -abort() was called at PC 0x400827a2 on core 1 (Issue #168)

You cant use OTA with a non-OTA partition scheme - Huge APP ( 3Mb No OTA/1MB SPIFFS).
