### ISSUE TITLE
FTP Server Connection Issue

### ISSUE THREAD

**Issue by maximagination1** [s60sc/ESP32-CAM_MJPEG2SD#171]
Hi there,

The code is working really well with my camera considering the update on the UI. Great work. However, I'm unable to get the recordings transferring to my new FTP server. The message I'm getting in the web server and serial monitor is: "Error opening ftp connection to ftp://..." - my IP address. "Unable to make ftp connection".

A little help would be appreciated. Thanks

**Comment by s60sc** [comment]
The ip address is not recognised, Try entering on a windows command line the following to check a response is received.
`ftp <your ip>`
