### ISSUE TITLE
my few issues

### ISSUE THREAD

**Issue by oldmaninsc** [s60sc/ESP32-CAM_MJPEG2SD#173]
windows picture/media/movie will NOT work. It showes only a black screen when viewing avi files. Makes one think your code dosent work. open files with VLC media player works.

would like a timer for the end of motion so could set a length to record after motion (10seconds)

would like an indicator when using battery power to know when recording. Just a dim blip on 
pin 33. or any gpio pin with a high value resister so an led would be dim. I could easily do this if I knew where in your code to turn on and off the GPIO.

cannot get the AP to show on phone or computer. Does it just show image when recording or does it send a image always? I log in with browser but never get a button console or an image.
I get 'onwifievent' started then stopped then started. and the 192.168.4.1  when i use the serial monitor

I have a stupid request... we have trails here and car theft. I used the 'random nerds esp32 cam' to record a series of photos to the sd card. This is great till they found the camera and took it. When I use the AP and connect just the camera to my phone all is great. I would like to use a second esp32 cam and connect to the other esp32 cam and record the streaming camera to the sd card. So one transmits only the image and another receives the image and stores it to the card. Now the camera can be stolen but I still have the images or video. Could you help in any even by pointing me in another direction

**Comment by s60sc** [comment]
> windows picture/media/movie will NOT work. It showes only a black screen when viewing avi files. Makes one think your code dosent work. open files with VLC media player works.

Contradictory

> would like a timer for the end of motion so could set a length to record after motion (10seconds)

Edit Config > Motion > Non movement to stop recording (secs)

> would like an indicator when using battery power to know when recording.

try something like digitalWrite(33, isCapturing) in processFrame(). Also need a flag to tell esp32 when using batt

> cannot get the AP to show on phone or computer.

not understood

> Could you help in any even by pointing me in another direction

try https://github.com/gemi254/ESP32-CAM_MJPEG2SD
