### ISSUE TITLE
Not getting static IP

### ISSUE THREAD

**Issue by maximagination1** [s60sc/ESP32-CAM_MJPEG2SD#176]
How do I get a static fixed IP address assigned to the camera? Any help on that would be appreciated.

**Comment by s60sc** [comment]
Edit Config > Wifi > enter values for static ip, router ip, dns ip

**Comment by maximagination1** [comment]
Thanks for this! It worked now.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
