### ISSUE TITLE
PORT

### ISSUE THREAD

**Issue by Makss8** [s60sc/ESP32-CAM_MJPEG2SD#177]
Hot to change straming port from 81 to 4138

**Comment by s60sc** [comment]
in `streamServer.cpp` change:

```
  config.server_port += 1;
  config.ctrl_port += 1;
```

**Comment by s60sc** [comment]
default web server port = 80
stream server port = default + 1 = 81
control port not used

`config.server_port = 4138;`

**Comment by s60sc** [comment]
See Readme

Compile with PSRAM enabled and the following Partition scheme:

ESP32 - Minimal SPIFFS (...)
ESP32S3 - 8M with spiffs (...)

**Comment by Makss8** [comment]
![image](https://user-images.githubusercontent.com/80113419/222912095-eee2620d-2471-4acd-88c2-035570e00390.png)
I changed port and now i dont see image stream: 
![image](https://user-images.githubusercontent.com/80113419/222912224-dc09866f-c368-4228-80ac-874d51f0d89c.png)
![image](https://user-images.githubusercontent.com/80113419/222912287-968cda93-1684-4af6-aff6-0c7763d6cd8c.png)

**Comment by s60sc** [comment]
you need to edit `mjpeg2sd.htm`

`        const streamUrl = baseHost + ':81';`

**Comment by Makss8** [comment]
Thank you sooo soooo much for your help! It works!!!!! If i want change webserver port i must change something here? static httpd_handle_t httpServer = NULL; // web server listens on port 80

**Comment by s60sc** [comment]
Add `config.server_port = n;` to `startWebServer()` to override default

**Comment by Makss8** [comment]
Why is the camera doing AP even though I turned off the Allow simultaneous AP option? Additionally, the AP is called ESP_76B155 and not Cam 
![image](https://user-images.githubusercontent.com/80113419/222916038-3eb44240-c83f-4a78-b3ae-4665b043d2fb.png)

**Comment by s60sc** [comment]
Press `Save `to make changes persistent

**Comment by Makss8** [comment]
I did the save a lot of times and restart, at first everything was ok and then this AP point was done. Even on the card in the config file there are data with the name of the AP point and it does the default name anyway

**Comment by MisiekDP** [comment]
I have totally this same problem with AP like @Makss8. I love this project but there is some errors too.
Problem with AP:
![image](https://user-images.githubusercontent.com/22171619/224474172-b89763bb-fae9-49bf-9f37-61afd0b317bb.png)
![image](https://user-images.githubusercontent.com/22171619/224474235-1f73f544-7604-404f-a951-262d7442e55c.png)


Btw. there is a problem with entered password - the AP is all the time unprotected and this is very unsafe for example in my situation.
The one way to secure is only to add authentication settings:
![image](https://user-images.githubusercontent.com/22171619/224474317-c8afa175-27fb-40c1-8e49-afcfebe5917b.png)
But is is not the best option for me and not works in all situations (for example I set login "a" and password "a", clicked "Save" and I blocked my ESP - not possible to get access, but with "admin" and "admin" it works).

**Comment by s60sc** [comment]
New version 8.5

**Comment by rbolero** [comment]
> Add `config.server_port = n;` to `startWebServer()` to override default

where can I find this startwebserver? is it on .ino file?

**Comment by s60sc** [comment]
In `appGlobals.h` change:

```
// web server ports
#define WEB_PORT 80 // app control
#define STREAM_PORT 81 // camera images
#define OTA_PORT 82 // OTA update
```

In` mjpeg2sd.htm` change:
```
const webPort = 80;
const otaPort = 82;
const streamPort = 81;
```
