### ISSUE TITLE
Wifi connection  error  

### ISSUE THREAD

**Issue by Mjz86** [s60sc/ESP32-CAM_MJPEG2SD#180]
The router  signal is -86dbm  and  ping fails so  ap is repeatedly  disconnecting

**Comment by Mjz86** [comment]
Another one  is that  you  cant set a password  for  ap  i dont know  if its a bug or im wrong

**Comment by Mjz86** [comment]
Another one  is that  you  cant set a password  for  ap  i dont know  if its a bug or im wrong

**Comment by s60sc** [comment]
Should be fixed now in 8.5
