### ISSUE TITLE
Switch on Lamp - lampLevel

### ISSUE THREAD

**Issue by Jampa25** [s60sc/ESP32-CAM_MJPEG2SD#183]
Turning on the lamp is not working, apparently the lampLevel variable, I changed it to 3 and now it works.
mjpeg2sd.cpp Line 362

if (lampAuto && nightTime) setLamp(lampLevel); // switch on lamp - does not work

if (lampAuto && nightTime) setLamp(3); // switch on lamp - it works

**Comment by s60sc** [comment]
The auto part was never fully implemented. I'll have a look.
