### ISSUE TITLE
Pins Usage

### ISSUE THREAD

**Issue by maximagination1** [s60sc/ESP32-CAM_MJPEG2SD#192]
Despite knowing the mentioned IO pins that are available on the ESP32-CAM for external sensors/loads, I'd still like to know if there are 3 pins apart from IO12, IO4 and IO33 that can be used to run a microphone. 

Would pins IO3 (RX), IO1 (TX) and IO0 (- Strapping pin) work as regular IO pins for an I2S Mic? If so, could you please advise how it is best wired with the 3 pins? If it's not possible, do you know how else I can get an I2S Mic connected to the ESP32-CAM AI thinker board without an IO extender chip? Considering there's already a couple of servo motors and a PIR motion sensor taking up 3 pins.

Your advice would be appreciated. Thanks.

**Comment by maximagination1** [comment]
Thanks for your reply.

Ok, this means I can only attach something like a voltage divider wire for
battery voltage monitoring or a temp sensor.

I couldn't figure out how to program my ESP32-C3-WROOM-02-N4 for the IO
extender as it's pinout is different than of other ESP32 chips. It programs
with different Strapping pins, I ended up failing to get it to work due to
a lack of guidance on it.

**Comment by s60sc** [comment]
voltage divider can only be used on pin 33 (only free adc)

**Comment by maximagination1** [comment]
Got it. So can I instead have a PIR motion sensor hooked up to pin 3?

**Comment by s60sc** [comment]
Should work, but disconnect pir during upload.
Your above comments dont mention pin 13 which is also available

**Comment by maximagination1** [comment]
Ok, thanks. I'll keep that in mind.

Pin 13 didn't work as it seems to be used up by the microSD card during
use. The web server would not load and it gave an SD error.
