### ISSUE TITLE
TLS support for mail notifications.

### ISSUE THREAD

**Issue by than-sad** [s60sc/ESP32-CAM_MJPEG2SD#193]
Hi! My mail server only works with TLS due to its more secure and new than SSL.

Is it posible to setup the mail notifications trow TLS instead of SSL? Or any plan to add compatibility in next versions?

Best regards and thanks for this great project!

**Comment by s60sc** [comment]
Implementing TLS would be an interesting learning experience but I don't have time in the short term

**Comment by than-sad** [comment]
I see, thanks anyway. 
I think this project is the best one I saw for ESP32-CAM but it seems that it's not very well known. It would be nice to give it more impact on the network. I'll think about something.
