### ISSUE TITLE
Edit MJPEG2SD.htm directly from device

### ISSUE THREAD

**Issue by than-sad** [s60sc/ESP32-CAM_MJPEG2SD#194]
Hi! I'm doing a UI modification to make it more useful in mobile phones including iPhone but remove SD, connect to MAC edit, put it back to ESP32-CAM to see the changes and repeat the process is boring.

Is there any way to edit htm directly from the device?

Best regards.
![Screenshot 2023-03-30 at 09 31 37](https://user-images.githubusercontent.com/50262726/228762513-15abae5d-cd11-4b9f-b733-e5bf80a74e12.png)

**Comment by s60sc** [comment]
You can upload modified htm and config file using ota

**Comment by than-sad** [comment]
Interesting I will try. Thanks for the tip ;)

**Comment by than-sad** [comment]
Also I see you use icons like text characters, not images, where can I find more?

**Comment by than-sad** [comment]
That's the keyword I was looking for. Thanks again ;)
