### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Makss8** [s60sc/ESP32-CAM_MJPEG2SD#195]
hi can you add an option to show the current time in any corner?  (in recordings and in live view)
![A407D629-FE7A-47A4-92F8-AD40D671AED2](https://user-images.githubusercontent.com/80113419/228946935-62b15864-f98f-4faf-88b8-d7001b7d74fc.jpeg)

**Comment by s60sc** [comment]
technically possible, but would require image processing by esp32 which would massively slow down frame rate. 
jpeg -> rgb -> add time -> jpeg

**Comment by s60sc** [comment]
,with regrard to this issue and your issue #191, you could use a PC as a proxy to receive the cam stream, apply a timestamp,  display the stream, then forward to the dvr. You would have to research it yourself though.

**Comment by s60sc** [comment]
see also this [fork](https://github.com/gemi254/ESP32-CAM_MJPEG2SD)

**Comment by s60sc** [comment]
I can add feature to deep sleep at night and wake on LDR

**Comment by s60sc** [comment]
sleep / wake in version 8.6.3
