### ISSUE TITLE
Insert SVG icons from SD card in MJPPEG2SD.htm

### ISSUE THREAD

**Issue by than-sad** [s60sc/ESP32-CAM_MJPEG2SD#196]
Hi,

I'm working in the IU redesign and I want to use SVG icons. I copied it to `/data/icons/*.svg` and called it in the htm like `<img src = "./icons/Close.svg"/>` but the /data folder contents aren't visible getting 404.

@s60sc how can I do it?

Regards.

**Comment by s60sc** [comment]
the request for content in the /data folder is handled by the web server, so for example to retrieve `configs.txt` write `src='/web?configs.txt'`
Dont think it will handle a folder hierarchy but you could try
See `webHandler(httpd_req_t* req)` in` webserver.cpp`

**Comment by than-sad** [comment]
Yes, again you are right. Copied to / and updated calls in htm and works. I wanted in /icons folder to don't mees too much. I will check the weberserver.cpp in the future to make it handle /

Thanks again ;)
