### ISSUE TITLE
OV7725 support

### ISSUE THREAD

**Issue by tennisparty** [s60sc/ESP32-CAM_MJPEG2SD#20]
Would it be possible to edit the code so it converts cameras which do not support JPEG? The OV7725 does not support JPEG but is very sensitive to infra-red light. Could you undertake a conversion to JPEG before the frames are used for the web stream and the MJPEGs?

**Comment by s60sc** [comment]
Technically possible with slow frame rate, but I'm focused on another project. Someone else is welcome to try.
