### ISSUE TITLE
Feature suggestion: Motion detection on specific time

### ISSUE THREAD

**Issue by than-sad** [s60sc/ESP32-CAM_MJPEG2SD#200]
Hi,

I miss the option to choose when activate the motion sensor by time, for example:

Every night from 1 am to 7 am. Saturday and Sunday all day, etc. To have an automation for that function.

Best regards.

**Comment by s60sc** [comment]
or modify this [fork](https://github.com/gemi254/ESP32-CAM_MJPEG2SD)
