### ISSUE TITLE
Help redesigning the UI

### ISSUE THREAD

**Issue by than-sad** [s60sc/ESP32-CAM_MJPEG2SD#202]
Hi!

I'm redesigning the UI and I know how I want it but my programing level isn't enough and I'm taking a lot of time searching and learning.

@s60sc Are you interested in help me and do it together?

Regards.
![UI](https://user-images.githubusercontent.com/50262726/230066199-73041a01-f7fe-4a35-b75c-85e4cb5e0fd0.png)

**Comment by s60sc** [comment]
I'm a C programmer, I actually dislike working on UIs and what I know is self taught.  Dont might giving occasional advice. The image size control looks good.

**Comment by than-sad** [comment]
Hi! Ok @s60sc thanks anyway.

If someone with javascript and HTM knowledge wants to help just let me know.

Regards.
