### ISSUE TITLE
Poor web performance

### ISSUE THREAD

**Issue by mrbell321** [s60sc/ESP32-CAM_MJPEG2SD#203]
I've got this on an AI-thinker ESP32-CAM and it's functional. Tho about 9 times out of 10, loading the web pages(either STA or AP) time out.
My router reports ~-50 to -30dBm/80-100% signal from the device and the ESP reports ~-60bDm to -40dBm. I think these are all reasonable numbers?

Additionally, sometimes on reboot it seems to forget about the SSID/password, hostname and other settings altogether. I thought it might be the SD card, but the same situation persists on 3 different SD cards that seem to work on other devices.
I tried putting the SSID and password directly into the code, that appears to do nothing as on a fresh install, I have to go to the AP and enter it manually.

Any suggestions

**Comment by s60sc** [comment]
The signal strength is ok so you must have significant signal interference.
