### ISSUE TITLE
ESP32 Cam wont start after flashing

### ISSUE THREAD

**Issue by fellpower** [s60sc/ESP32-CAM_MJPEG2SD#204]
- ESP32-Cam board, with stock cam
- Arduino IDE 2.04
- ESP32 in Boardmanager: 2.0.6

My ESP32 is confed like that:

only changed partitionscheme to "1,9MB APP with OTA / 190kb SPIFFS" because the default 4Mb wont work. Code is too big is the IDE saying.

Now, the flash is done, removed the cable between ID0 and GND - but the ESP wont start

Error is as follow

00:00:06.378 setup] =============== Starting ===============
[00:00:06.426 infoSD] SD card type SDHC, Size: 7680MB, Used space: 0MB, of total: 7660MB
[00:00:06.427 checkFreeSpace] Storage free space: 7659MB
[00:00:06.637 prepCam] Camera init OK for model OV2640 on board CAMERA_MODEL_AI_THINKER
[00:00:06.684 loadConfig] Load config
[00:00:06.785 updateAppStatus] Enabling motion detection
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13924
ho 0 tail 12 room 4
load:0x40080400,len:3600
entry 0x400805f0

What im doing wrong?

**Comment by s60sc** [comment]
Cant say, possible hardware issue eg GPIO0 conflict which is used by cam. Disconnect GPIO0 as soon as download starts.
