### ISSUE TITLE
failed to ping gatway restart wifi

### ISSUE THREAD

**Issue by DJprasenjit** [s60sc/ESP32-CAM_MJPEG2SD#205]
stream breaking. always coming this " Failed to ping gatway, wifi restart"
tell me a solution

**Comment by s60sc** [comment]
weak wifi see item 7 in this [guide ](https://randomnerdtutorials.com/esp32-cam-troubleshooting-guide/)

**Comment by DJprasenjit** [comment]
but its works some time and some time that error comes,. wifi signal is constant -50 to 55dBm then why this error coming

**Comment by s60sc** [comment]
Signal interference

**Comment by s60sc** [comment]
maybe inverter causing interference
