### ISSUE TITLE
Compilation error: exit status 1

### ISSUE THREAD

**Issue by rbolero** [s60sc/ESP32-CAM_MJPEG2SD#206]
Please help with this issue. It's been a month since I started uploading this code but still no luck. Need help what's wrong with these:

Thanks a lot.

In file included from c:\users\koko\appdata\local\arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\include\c++\8.4.0\locale:41,
                 from c:\users\koko\appdata\local\arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\include\c++\8.4.0\regex:44,
                 from C:\Users\koko\Downloads\Compressed\ESP32-CAM_MJPEG2SD-master\ESP32-CAM_MJPEG2SD\globals.h:25,
                 from C:\Users\koko\Downloads\Compressed\ESP32-CAM_MJPEG2SD-master\ESP32-CAM_MJPEG2SD\appGlobals.h:6,
                 from C:\Users\koko\Downloads\Compressed\ESP32-CAM_MJPEG2SD-master\ESP32-CAM_MJPEG2SD\ESP32-CAM_MJPEG2SD.ino:8:
c:\users\koko\appdata\local\arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\include\c++\8.4.0\bits\locale_facets_nonio.h:2010:10: fatal error: bits/messages_members.h: No such file or directory
 #include <bits/messages_members.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Compilation error: exit status 1

**Comment by s60sc** [comment]
Corrupt installation, do a clean instal of latest  [esp32 library](https://github.com/espressif/arduino-esp32)
