### ISSUE TITLE
Unsecured Access Point after connecting to wifi

### ISSUE THREAD

**Issue by JackGM** [s60sc/ESP32-CAM_MJPEG2SD#207]
There seems to be an issue with my setup where the wireless access points used to setup the cameras in the first place, remain active and without password protection. I assume this means that people could jump onto the network and see the footage/adjust the camera settings?
Thanks!

**Comment by JackGM** [comment]
Found the settings in the config files. Could be worth setting a initial password which can be changed, so it has a basic level of protection

**Comment by JackGM** [comment]
The access points still seem to be unsecured and SSIDs unchanged after changing the config and rebooting.

**Comment by s60sc** [comment]
press save before reboot to make changes persistent
