### ISSUE TITLE
Playback error

### ISSUE THREAD

**Issue by YapCK45** [s60sc/ESP32-CAM_MJPEG2SD#208]
I was playing back the recorded video and I got this error message:
'[01:12:27.639 ERROR @ utilsFS.cpp:265] Deletion of /System Volume Information not permitted'

I could not initiate recording but I could perform other functions such as Start Stream. A reboot resolves the problem but all the previous recordings were not longer there. Apparently, they had been erased.

**Comment by s60sc** [comment]
Issue #199 bug in previous version
