### ISSUE TITLE
Sketch usage

### ISSUE THREAD

**Issue by FrancescoMontedori** [s60sc/ESP32-CAM_MJPEG2SD#209]
Hi, thanks for sharing your project. I would like to use the MJPEG2SD sketch to record .avi video at SVGA resolution and 20 FPS with connected I2S mic. 
I would like to add a physical button that allows to start and stop recording on SD memory, in order to leave the esp32s3 alive and record multiple video files.
I read from your README.md:
"A recording is generated either by the camera itself detecting motion as given in the  by holding a given pin high (kept low by internal pulldown when released". 
Which PIN has to be set as high to start/stop recording?
More over, Which pin should i use for the I2S microphone?
Sorry if this are dumb questions, but i'm quiet new to C language.
Thanks

**Comment by FrancescoMontedori** [comment]
Hi, thanks a lot for the quick answer! I manged to connect the button and assign it in the web interface as PIN 12. I simply connected a button that, when clicked, connect the PIN 12 to the 3v3. 
From the serial monitor of the arduino ide i can see that the esp32s3 is waiting for the PIN 12 to be Pulled Up. 

![esp32_s3_cam_2](https://user-images.githubusercontent.com/68377563/232753835-3f718980-70bd-435e-ac56-8e88cc6a682f.png)

When i press the button the log show this output:

![esp32_s3_cam](https://user-images.githubusercontent.com/68377563/232753958-9e536f41-7443-405f-bd86-175e8e057e3a.png)

But then, when i press the button again (remove the pullup for PIN 12 and theoretically stop recording) i receive the following message from the serial monitor:

![esp32s3cam](https://user-images.githubusercontent.com/68377563/232754184-d3ced3a4-06db-4fb0-b983-fb8de2d0850b.png)

It is trying to record an .avi video of 640x480 at 20 FPS (as specified in the web interface), but it gets only 0.1 FPS.

Any suggestion?

**Comment by s60sc** [comment]
Need to keep pin high for duration of recording, use latch button
You can also use this button on the web page

![Screenshot 2023-04-18 121626](https://user-images.githubusercontent.com/23615220/232760963-de1f02fc-5075-4b4b-b54e-3f67695147d2.png)

**Comment by FrancescoMontedori** [comment]
I and thanks. I was already able to record at desired fps from the web interface as i show in the following pic.

![ess](https://user-images.githubusercontent.com/68377563/232792187-f915cb8e-d1e0-4182-b70a-6dd2c5ce1328.png)
 
Moreover I am actually already using a Latch button and  I attach the diagram i used to put and keep the pin high:

![es](https://user-images.githubusercontent.com/68377563/232791449-349ab3ae-3007-44be-8a9f-732a5a8c4c2f.png)

When i reset the ESP i can read from the serial button that the PIR start/stop recording is enabled and that it is waiting for PIN 12 to be connected to 3,3v to start rec. 
![esss](https://user-images.githubusercontent.com/68377563/232795430-0bac36ff-b8f1-4348-8bfb-b49e6977a021.png)

However when i press the button the dotted line (wich shows that video is recording) stops after 2/3 dot and i still get the same problem: The FPS are 0.1 and the video is not reproducible

**Comment by s60sc** [comment]
The button is not being kept high, try using a jumper wire instead

**Comment by FrancescoMontedori** [comment]
Hi, I managed to record at proper FPS and start stop record with latch button connected on PIR PIN. The problem was the selected PIN. I was trying to pull the PIN 12, i changed to PIN 14 and now it works like a charm. 

Thank you so much for the support.

**Comment by s60sc** [comment]
Good to hear.
In your original comment you mentioned using the esp32s3. This would explain the problem with pin 12 which is free on esp32 but used by the camera on esp32s3.
