### ISSUE TITLE
Get fps API

### ISSUE THREAD

**Issue by quockhanh1198** [s60sc/ESP32-CAM_MJPEG2SD#21]
Hi, your project is very wonderful. So, I would like to view fps API by http_GET when I configured it in arduino code. Can you suggest me ? Thank you so much !

**Comment by s60sc** [comment]
Thanks
I'm not sure what your question means. The fps value is returned in JSON format in response to a GET, eg {fps: "5"}

**Comment by quockhanh1198** [comment]
Thanks for your feedback. More specifically, I want to GET fps api in the browser and be able to change the fps parameters with the api itself without having to adjust from the fps setting on the streaming web, eg {http://192.168.1.1/control ? var = fps & val = 10 to http://192.168.1.1/control?var=fps&val=5}.

**Comment by s60sc** [comment]
You seem to have answered your own question, just type http://192.168.1.1/control?var=fps&val=5 into the browser, or send from from your own app.

**Comment by quockhanh1198** [comment]
Thank you, sorry but I want to ask you 1 question please. Moreover, If I don't want to record video from SD card, I just want to stream on browser, can you suggest me, bro ?

**Comment by s60sc** [comment]
if you just want to stream, use the Arduino sketch: File > Examples > ESP32 > Camera > CameraWebServer
It has the same api.

**Comment by quockhanh1198** [comment]
I tried that, but it has no function to configure fps and get fps api in the browser.
