### ISSUE TITLE
Failed to open /~current

### ISSUE THREAD

**Issue by YapCK45** [s60sc/ESP32-CAM_MJPEG2SD#211]
v8.6.3
Folder cannot be deleted. ERROR @ utilsFS.cpp:260 Failed to open /~current if selected from **Go to current (today)**
Files can be deleted individually.
Folder can be deleted after ESP reboot.

If **List folder** is used and a folder is selected, there is no problem and all the files in the folder are deleted one by one.

**Comment by s60sc** [comment]
Current folder can be deleted by selecting its date from list folder.
I'll look at making it work when current (or previous) is selected

**Comment by s60sc** [comment]
Version 8.6.4 should fix
