### ISSUE TITLE
Cannot connect to server .......

### ISSUE THREAD

**Issue by pratik001010** [s60sc/ESP32-CAM_MJPEG2SD#213]
After uploading code to the board , we cannot connect to the server as long as tthe sd card is installed on the board , if sd card is ejected from the board then only ip is loaded with error message saying check your sd card

**Comment by s60sc** [comment]
is the data folder downloaded to sd card?

**Comment by pratik001010** [comment]
Yes sir ,, still cannot figure out why my board cannot connect to server without ejecting sd card

**Comment by lefake** [comment]
Getting the same issue... 

This is with the SD Card (with the data folder)
![image](https://user-images.githubusercontent.com/9541118/235543441-18120e31-3fe4-4631-8d52-4961d2c41963.png)

This is without it
![image](https://user-images.githubusercontent.com/9541118/235543506-186725be-721f-4589-8740-a0c3b8542164.png)
