### ISSUE TITLE
No Station SSID

### ISSUE THREAD

**Issue by Cezarion11** [s60sc/ESP32-CAM_MJPEG2SD#215]
Hi,

I have a stupid question, I am getting this error
WARN setWifiSTA] No Station SSID provided, use AP

The SSID and pass should be added in the globals file? Or in the configs file SSDI name and password?

Thank you.

**Comment by s60sc** [comment]
Connect to ap to enter station details

**Comment by Cezarion11** [comment]
When I try to connect to the IP 192.168.4.1 Wifi AP SSID: ESP-CAM_MJPEG_2C81C115B80C started, use 'http://192.168.4.1' to connect> I get this site can't be reached.
Do I need to add the ssid and password in the data folder on ESp32 sd card?

Thanks.

**Comment by s60sc** [comment]
You need to connect to SSID: ESP-CAM_MJPEG_2C81C115B80C first

**Comment by Cezarion11** [comment]
It works, thanks.
