### ISSUE TITLE
What Arduino Board Name to use with ESP-CAM?

### ISSUE THREAD

**Issue by gwinterhalter** [s60sc/ESP32-CAM_MJPEG2SD#216]
The The AI Thinker ESP-CAM does not support PSRAM, yet this sketch requires it. What Board Name should be selected to enable PSRAM when using a ESP-CAm with PSRAM?

Thanks

PS thanks for making this contribution its very robust.

Greg

**Comment by s60sc** [comment]
If your AI Thinker ESP-CAM board does not support psram it is either faulty or a fake.
