### ISSUE TITLE
SD CRAD Mount failed

### ISSUE THREAD

**Issue by ram-123455** [s60sc/ESP32-CAM_MJPEG2SD#218]
just after uploading the code i have this on my serial terminal

E (511) sdmmc_common: sdmmc_init_ocr: send_op_cond (1) returned 0x107 E (512) vfs_fat_sdmmc: sdmmc_card_init failed (0x107). [00:00:22.394 ERROR @ utilsFS.cpp:65] SD card mount failed

**Comment by s60sc** [comment]
hardware problem- card, reader, power supply, pin conflict, board damage, etc.

**Comment by ram-123455** [comment]
Not able to resolve . Can you please suggests what settings should be done for SD card as per your code?

**Comment by s60sc** [comment]
nothing to do with code - hardware problem
