### ISSUE TITLE
SD card performance

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [s60sc/ESP32-CAM_MJPEG2SD#223]
Will a 4GB SD card provide better performance compared to a 16GB or 32GB card?

There's been some debate about this question and I was wondering if you had an answer.

**Comment by s60sc** [comment]
[Write speed](https://www.kingston.com/unitedkingdom/en/blog/personal-storage/memory-card-speed-classes) is what matters - depends on class number, and whether card is genuine.

**Comment by LevitatingBusinessMan** [comment]
Right, thanks
