### ISSUE TITLE
Playback is slow

### ISSUE THREAD

**Issue by sameSEA** [s60sc/ESP32-CAM_MJPEG2SD#224]
I use ESP32-Cam
Camera records 800x600 a 5fps

Playing recorded files is really slow, like 5x slower.
The live view plays ok, there doesn't seem to be any issues with connectivity.
Downloaded files also play normally.

**Comment by s60sc** [comment]
playback speed depends on sd card and browser connection.

**Comment by sameSEA** [comment]
Assuming that live view is ok, it is sd issue?

**Comment by s60sc** [comment]
Each frame has to be read from SD. Better to download.

**Comment by sameSEA** [comment]
Can SD be used in 4 pin mode if I don't use a PIR or lamp?
I assume that would fix preview?

Or, using ESP32S3 can fix that?
Or, is there anything that makes preview at original speed?

**Comment by s60sc** [comment]
4 line or S3 wont help.
Limiting factor is sd card speed - use a genuine class 10.
But why not download or ftp instead?

**Comment by sameSEA** [comment]
There ara hundreds of motions recorded every day. 
Preview before downloading would be very helpful.
