### ISSUE TITLE
Why is the OTA Upload option is for?

### ISSUE THREAD

**Issue by DJprasenjit** [s60sc/ESP32-CAM_MJPEG2SD#226]
I tried sevaral time to update new version through OTA but its failed every time. i dont know what i am doing wrong
Please tell me what is the process of Upload the code by OTA
I just compiled the update code on arduino IDE and took the bin file and tried to upload on it, but its not working at all

**Comment by s60sc** [comment]
Compile with correct partition scheme

**Comment by DJprasenjit** [comment]
yes i compiledwith correct partition scheme and its upload and works fine with uart port
but OTA upload failed. i dont know why? is OTA function is working?

**Comment by DJprasenjit** [comment]
i selected 3MB no OTA partition of AI THINKER ESP32 board

**Comment by s60sc** [comment]
OTA can't work if you selected no OTA partition!
