### ISSUE TITLE
How do I put the scheduling function in?

### ISSUE THREAD

**Issue by beodeulsoft** [s60sc/ESP32-CAM_MJPEG2SD#227]
In order to use this device on the desk in the office, I want to disable motion detection during business hours, so I want to put in a schedule function.
![esp32s3_schedule](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/1763473/7b0621e0-7ddf-4ba7-a1cc-e811b61b56eb)
#MJPEG2SD.htm
&lt;nav class="quick-nav" id="scheduler" name="weekly-schedule"&gt;?&lt;/nav&gt;
...
&lt;nav class="menu panel" id="weekly-schedule"&gt;
                &lt;input type="checkbox" id="schedule-cb" class="menu-action"&gt;
                &lt;div class="pin-menu" title="Pin / unpin menu"&gt;?&lt;/div&gt;
                &lt;label for="schedule-cb" class="nav-toggle"&gt;?&nbsp;&nbsp;Weekly Schedule&nbsp;&nbsp;&lt;/label&gt;
                &lt;div class='addButtons'&gt;&lt;/div&gt;
                &lt;div&gt;
                  &lt;div class="input-group" id="week0-group"&gt;
                    &lt;label for="week0"&gt;Monday&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="week0" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting day of the week" class="slider" for="week0"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="week1-group"&gt;
                    &lt;label for="week1"&gt;Tuesday&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="week1" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting day of the week" class="slider" for="week1"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="week2-group"&gt;
                    &lt;label for="week2"&gt;Wednesday&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="week2" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting day of the week" class="slider" for="week2"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="week3-group"&gt;
                    &lt;label for="week3"&gt;Thursday&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="week3" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting day of the week" class="slider" for="week3"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="week4-group"&gt;
                    &lt;label for="week4"&gt;Friday&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="week4" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting day of the week" class="slider" for="week4"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="week5-group"&gt;
                    &lt;label for="week5"&gt;Saturday&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="week5" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting day of the week" class="slider" for="week5"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="week6-group"&gt;
                    &lt;label for="week6"&gt;Sunday&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="week6" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting day of the week" class="slider" for="week6"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="vsep"&gt;&lt;/div&gt;
                  &lt;div class="input-group" id="day00-group"&gt;
                    &lt;label for="day00"&gt;00:00 ~ 01:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day00" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day00"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day01-group"&gt;
                    &lt;label for="day01"&gt;01:00 ~ 02:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day01" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day01"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day02-group"&gt;
                    &lt;label for="day02"&gt;02:00 ~ 03:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day02" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day02"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day03-group"&gt;
                    &lt;label for="day03"&gt;03:00 ~ 04:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day03" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day03"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day04-group"&gt;
                    &lt;label for="day04"&gt;04:00 ~ 05:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day04" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day04"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day05-group"&gt;
                    &lt;label for="day05"&gt;05:00 ~ 06:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day05" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day05"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day06-group"&gt;
                    &lt;label for="day06"&gt;06:00 ~ 07:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day06" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day06"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day07-group"&gt;
                    &lt;label for="day07"&gt;07:00 ~ 08:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day07" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day07"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day08-group"&gt;
                    &lt;label for="day08"&gt;08:00 ~ 09:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day08" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day08"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day09-group"&gt;
                    &lt;label for="day09"&gt;09:00 ~ 10:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day09" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day09"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day10-group"&gt;
                    &lt;label for="day10"&gt;10:00 ~ 11:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day10" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day10"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day11-group"&gt;
                    &lt;label for="day11"&gt;11:00 ~ 12:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day11" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day11"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day12-group"&gt;
                    &lt;label for="day12"&gt;12:00 ~ 13:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day12" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day12"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day13-group"&gt;
                    &lt;label for="day13"&gt;13:00 ~ 14:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day13" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day13"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day14-group"&gt;
                    &lt;label for="day14"&gt;14:00 ~ 15:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day14" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day14"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day15-group"&gt;
                    &lt;label for="day15"&gt;15:00 ~ 16:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day15" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day15"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day16-group"&gt;
                    &lt;label for="day16"&gt;16:00 ~ 17:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day16" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day16"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day17-group"&gt;
                    &lt;label for="day17"&gt;17:00 ~ 18:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day17" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day17"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day18-group"&gt;
                    &lt;label for="day18"&gt;18:00 ~ 19:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day18" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day18"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day19-group"&gt;
                    &lt;label for="day19"&gt;19:00 ~ 20:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day19" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day19"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day20-group"&gt;
                    &lt;label for="day20"&gt;20:00 ~ 21:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day20" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day20"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day21-group"&gt;
                    &lt;label for="day21"&gt;21:00 ~ 22:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day21" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day21"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day22-group"&gt;
                    &lt;label for="day22"&gt;22:00 ~ 23:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day22" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day22"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                  &lt;div class="input-group" id="day23-group"&gt;
                    &lt;label for="day23"&gt;23:00 ~ 24:00&lt;/label&gt;
                    &lt;div class="switch"&gt;
                      &lt;input id="day23" type="checkbox" checked="checked"&gt;
                      &lt;label title="Enable detecting time of the day" class="slider" for="day23"&gt;&lt;/label&gt;
                    &lt;/div&gt;
                  &lt;/div&gt;
                &lt;/div&gt;

#appSpecific.cpp
else if(!strcmp(variable, "week0")) week[0] = (intVal) ? true : false;
  else if(!strcmp(variable, "week1")) week[1] = (intVal) ? true : false;
  else if(!strcmp(variable, "week2")) week[2] = (intVal) ? true : false;
  else if(!strcmp(variable, "week3")) week[3] = (intVal) ? true : false;
  else if(!strcmp(variable, "week4")) week[4] = (intVal) ? true : false;
  else if(!strcmp(variable, "week5")) week[5] = (intVal) ? true : false;
  else if(!strcmp(variable, "week6")) week[6] = (intVal) ? true : false;
  else if(!strcmp(variable, "day00")) day[0] = (intVal) ? true : false;
  else if(!strcmp(variable, "day01")) day[1] = (intVal) ? true : false;
  else if(!strcmp(variable, "day02")) day[2] = (intVal) ? true : false;
  else if(!strcmp(variable, "day03")) day[3] = (intVal) ? true : false;
  else if(!strcmp(variable, "day04")) day[4] = (intVal) ? true : false;
  else if(!strcmp(variable, "day05")) day[5] = (intVal) ? true : false;
  else if(!strcmp(variable, "day06")) day[6] = (intVal) ? true : false;
  else if(!strcmp(variable, "day07")) day[7] = (intVal) ? true : false;
  else if(!strcmp(variable, "day08")) day[8] = (intVal) ? true : false;
  else if(!strcmp(variable, "day09")) day[9] = (intVal) ? true : false;
  else if(!strcmp(variable, "day10")) day[10] = (intVal) ? true : false;
  else if(!strcmp(variable, "day11")) day[11] = (intVal) ? true : false;
  else if(!strcmp(variable, "day12")) day[12] = (intVal) ? true : false;
  else if(!strcmp(variable, "day13")) day[13] = (intVal) ? true : false;
  else if(!strcmp(variable, "day14")) day[14] = (intVal) ? true : false;
  else if(!strcmp(variable, "day15")) day[15] = (intVal) ? true : false;
  else if(!strcmp(variable, "day16")) day[16] = (intVal) ? true : false;
  else if(!strcmp(variable, "day17")) day[17] = (intVal) ? true : false;
  else if(!strcmp(variable, "day18")) day[18] = (intVal) ? true : false;
  else if(!strcmp(variable, "day19")) day[19] = (intVal) ? true : false;
  else if(!strcmp(variable, "day20")) day[20] = (intVal) ? true : false;
  else if(!strcmp(variable, "day21")) day[21] = (intVal) ? true : false;
  else if(!strcmp(variable, "day22")) day[22] = (intVal) ? true : false;
  else if(!strcmp(variable, "day23")) day[23] = (intVal) ? true : false;

#mjpeg2sd.cpp
bool week[7];
bool day[24];

void getWeekHour(tm * timeinfo) {
    struct timeval tv;
    gettimeofday(&tv, NULL);

    time_t rawtime = tv.tv_sec;
    timeinfo = localtime (&rawtime);
}
/**************** timers & ISRs ************************/

static void IRAM_ATTR frameISR() {
  // check weekly schedule 
  struct tm* timeinfo;;
  getWeekHour(timeinfo);
  int nWeek = timeinfo->tm_wday;
  if(!week[nWeek]) 
  {
    LOG_ERR("frameISR: Week %d is not scheduled", nWeek);
    delay(1000);
    return;
  }
  int nHour = timeinfo->tm_hour;
  if(!day[nHour]) 
  {
    LOG_ERR("frameISR: Time %d is not scheduled", nHour);
    delay(1000);
    return;
  }
  // interrupt at current frame rate
  BaseType_t xHigherPriorityTaskWoken = pdFALSE;
  vTaskNotifyGiveFromISR(captureHandle, &xHigherPriorityTaskWoken); // wake capture task to process frame
  if (isPlaying) xSemaphoreGiveFromISR (playbackSemaphore, &xHigherPriorityTaskWoken ); // notify playback to send frame
  if (xHigherPriorityTaskWoken == pdTRUE) portYIELD_FROM_ISR();
}
...
static void startSDtasks() {
  //init schedule
  for(int i=0; i < 7; i++)
      week[i] = true;
  for(int i=0; i < 24; i++)
      day[i] = true;
  // tasks to manage SD card operation
  xTaskCreate(&captureTask, "captureTask", 1024 * 4, NULL, 5, &captureHandle);
  xTaskCreate(&playbackTask, "playbackTask", 1024 * 4, NULL, 4, &playbackHandle);
  sensor_t * s = esp_camera_sensor_get();
  fsizePtr = s->status.framesize; 
  setFPS(frameData[fsizePtr].defaultFPS); // initial frames per second  
  debugMemory("startSDtasks");
}

After working on the above, I uploaded it to the esp32-s3 cam board, and the web server is not working properly. Even if I change the location of the getWeekTime function, I can't save the schedule information even if I press the save button.

#define MAX_CONFIGS 130 // > number of entries in configs.txt

I changed the above value but it still doesn't work, is there any other good way?

**Comment by beodeulsoft** [comment]
It's hard because I'm not a web developer.
Thank you.

**Comment by s60sc** [comment]
one thought, the `configs.txt` file will not be updated unless the data items already exist in it, so you need to ensure you have added the new data items in `configs.txt` in the correct format, eg:
`week0~0~98~~na `
where `week0` is var name, `0` is initial value (false)

**Comment by beodeulsoft** [comment]
Thank you for your advise.

**Comment by beodeulsoft** [comment]
Maybe it was a pointer problem before, but the mcu kept rebooting, but it works when I fix the function that checks the schedule as below.

int arrWeek[] = {1,1,1,1,1,1,1};
int arrDay[] = {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1};

void* getWeekHour() {
   struct timeval tv;
   gettimeofday(&tv, NULL);

   return localtime(&tv.tv_sec);
}

static boolean processFrame() {
  if(timeSynchronized) //init ntp server?
  {
    // check weekly schedule 
    struct tm* timeinfo = (tm*)getWeekHour();
    int nWeek = timeinfo->tm_wday;
    if(arrWeek[nWeek] == 0) 
    {
      LOG_ERR("processFrame: Week %d is not scheduled", nWeek);
      //delay(100);
      return false;
    }
    int nHour = timeinfo->tm_hour;
    if(arrDay[nHour] == 0) 
    {
      LOG_ERR("processFrame: Time %d is not scheduled", nHour);
      //delay(100);
      return false;
    }
  } 
...
}
