### ISSUE TITLE
Motion not working in night mode when Lamp enabled.

### ISSUE THREAD

**Issue by camow7** [s60sc/ESP32-CAM_MJPEG2SD#230]
Testing with latest version of code as of 17/06/2023. It seems the motion is not triggered at night mode when the lamp is enabled. Is this intentional? I would think if the lamp is on you would want motion enabled even though it's night time?

**Comment by camow7** [comment]
I have just realized the work around to this is to adjust sensitivity until the lamp version of your night time shot is greater than your setting for night.

**Comment by s60sc** [comment]
on hols, so not able to check at this time

**Comment by s60sc** [comment]
Actually nighttime setting doesnt make sense, I'll remove it from next release.

**Comment by s60sc** [comment]
removed
