### ISSUE TITLE
SD Card

### ISSUE THREAD

**Issue by bjlah** [s60sc/ESP32-CAM_MJPEG2SD#231]
I always get : [00:00:07.279 ERROR @ setupAssist.cpp:86] Open failed: /data/configs.txt

I alredy copied the data folder into the sd card, an formatet it to fat32.
Its a 4gb intenso. I really dont know why its not working, hope somebody kann help.

Thank you!

**Comment by bjlah** [comment]
Can somebody please help?

thank you

**Comment by s60sc** [comment]
Are you sure the sd card contains a folder named `data`, and this folder contains a file called `configs.txt` with content.
if so cannot help further.

**Comment by DJprasenjit** [comment]
cope the data folder to sd card from the code folder then you got no such error
