### ISSUE TITLE
How should the SD card be connected?

### ISSUE THREAD

**Issue by B6dem** [s60sc/ESP32-CAM_MJPEG2SD#233]
I'm using the ESP32-WROVER module, also known as the Freenove ESP32-WROVER CAM board.

As it does not have an SD card slot, I got an external SD card adapter with CS, MOSI, CLK, MISO pins.
I don't know how to connect it to the ESP32-WROVER.How should I connect it in order to work with this code?

**Comment by s60sc** [comment]
that board is not supported. You would have to define all the pins in `camera_pins.h`
