### ISSUE TITLE
exit status 1 ping/ping_sock.h: No such file or directory

### ISSUE THREAD

**Issue by 3hossein** [s60sc/ESP32-CAM_MJPEG2SD#239]
hi
please help me

**Comment by s60sc** [comment]
[see readme](https://github.com/s60sc/ESP32-CAM_MJPEG2SD#:~:text=NOTE%3A%20If%20you%20get%20compilation%20errors%20you%20need%20to%20update%20your%20arduino%2Desp32%20library%20in%20the%20IDE%20using%20Boards%20Manager)

**Comment by DJprasenjit** [comment]
sir after i updated to new version its started lagging while streaming and recording slow, i used 1.9FS and OTA partition. please help me fix it. i have another cam running old version of it but its working fine. but new update has some issue .
