### ISSUE TITLE
Startup Failure: Check SD card inserted

### ISSUE THREAD

**Issue by maximagination1** [s60sc/ESP32-CAM_MJPEG2SD#241]
Hi, I and many other people in the comments of my YouTube videos face the same error message when using the ESP32-CAM (in the web server). "Startup Failure: Check SD card inserted" and a blank page.

What to change so this issue gets cleared? 

Thanks.

**Comment by s60sc** [comment]
May be a [camera board selection problem](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/issues/219#issuecomment-1627785417) causing pin conflict

**Comment by maximagination1** [comment]
Commenting out default camera models in "appGlobals.h" and uncommenting only the board I was using below (XIAO ESP32S3) seemed to do the trick. Thanks!
