### ISSUE TITLE
asking about forks....

### ISSUE THREAD

**Issue by anonytech1** [s60sc/ESP32-CAM_MJPEG2SD#242]
am i allowed to ask about some forks of this project other pople made like the multiclient one as i dont seem to be able to connect the cam to the server

**Comment by s60sc** [comment]
You'll need to contact @gemi254

**Comment by anonytech1** [comment]
may i know how? as his fork disabled issues

**Comment by gemi254** [comment]
Fixed the fork disabled issues, and updated to v 8.8a but cannot make it working with tornado 6.3.3
