### ISSUE TITLE
Suggestion: small improvement on checkMotion

### ISSUE THREAD

**Issue by RibeiroSantos** [s60sc/ESP32-CAM_MJPEG2SD#25]
Hi,

I think if we change the `if (changeCount> moveThreshold)` code, in motionDetect.cpp-> checkMotion (), into the loop `for (int i = 0; i <num_pixels; i ++)` , the motion detection will be faster, in the cases where the changes are at the "beginning" of the frame, because it will not be necessary to go through the entire frame. 

Thanks for sharing your work.

**Comment by s60sc** [comment]
Thanks, I'll take a look

**Comment by s60sc** [comment]
The loop is also used to calculate the light level and generate debug data so a change would not be straightforward
