### ISSUE TITLE
Framesize always SVGA regardless of config settings

### ISSUE THREAD

**Issue by OldYin** [s60sc/ESP32-CAM_MJPEG2SD#250]
Changes in file: ESP32-CAM_MJPEG2SD.ino may have caused a minor issue.

The order of ...

  // Load saved user configuration
  loadConfig();

  // initialise camera
  prepCam();

has recently changed. 
As a result, the line...       

      //drop down frame size for higher initial frame rate
      s->set_framesize(s, FRAMESIZE_SVGA);

in prepCam(); now overrides the framesize defined in any configuration after a reboot.

swapping the order of  loadConfig(); &  prepCam(); back again corrects this.

**Comment by s60sc** [comment]
Thanks, I'll investigate

**Comment by s60sc** [comment]
Should be fixed

**Comment by OldYin** [comment]
As far as the issue I was having with the framesize, that does indeed appear to be sorted. Thank you :)
