### ISSUE TITLE
Unable to download MJPEG2SD.htm file

### ISSUE THREAD

**Issue by bao2211** [s60sc/ESP32-CAM_MJPEG2SD#252]
When i connected to wifi and try to connect to web server got the error: "File does not exist or cannot be opened: /data/MJPEG2SD.htm"
even thought i have copy the data folder to the sd card
then i see that the log output: 
17:23:21.088 -> [00:00:12.268 wgetFile] Downloading /data/MJPEG2SD.htm from https://raw.githubusercontent.com/s60sc/ESP32-CAM_MJPEG2SD/master/data/MJPEG2SD.htm
17:23:21.757 -> [00:00:12.959 ERROR @ setupAssist.cpp:79] Download failed, error: connection refused 
17:23:21.804 -> [00:00:12.982 wgetFile] Downloading /data/MJPEG2SD.htm from https://raw.githubusercontent.com/s60sc/ESP32-CAM_MJPEG2SD/master/data/MJPEG2SD.htm
17:23:22.024 -> [00:00:13.240 ERROR @ setupAssist.cpp:79] Download failed, error: connection refused

after that i open the sd card i see that the MJPEG2SD.htm got remove

**Comment by s60sc** [comment]
you need an internet connection so that app knows its got most recent version of files
