### ISSUE TITLE
Need help with compilation on a esp32-s3 

### ISSUE THREAD

**Issue by PhilippeLx** [s60sc/ESP32-CAM_MJPEG2SD#255]
Which board to use for the Freenove esp32-s3-wroom module in arduino compiler ?

**Comment by s60sc** [comment]
S3 dev board

**Comment by PhilippeLx** [comment]
Yes i found , the issue.  Using ESP32S3 DEV Module. Also as mentioned it needed to set psram to OPI PSRAM with Partition Scheme 8mb with spliff. Also the on initial boot , the installation sets an .htm file for the web server front-end. But the file extension should be .html , i just copy pasted it to .html and it resolved the issue.
