### ISSUE TITLE
fmt2jpg() failed in motiondetect.cpp

### ISSUE THREAD

**Issue by TheDKey** [s60sc/ESP32-CAM_MJPEG2SD#256]
Motion detection works sometimes but most of the time failed in my case.

When it failed, it would show plain black on screen streaming with "Show motion" turned on.

And about 3 seconds, it would show error message that, in motiondetect.cpp, fmt2jpg failed.

I have tried to played around with the setting but nothing seemed to help.

How can I fix this?

**Comment by s60sc** [comment]
Corrupt image from camera

**Comment by TheDKey** [comment]
I have switched to a new module and new SD Card but the problem still persists.

I will close this issue for now and allow myself more time to look into it. Will start the whole process from start.
