### ISSUE TITLE
option to make files/folders readable

### ISSUE THREAD

**Issue by CazYokoyama** [s60sc/ESP32-CAM_MJPEG2SD#259]
I want to have a club website which

1. is browsed by club members
2. have ftp uploaded files

The ftp uploaded files are created as no read permission for group and others. Therefore the files are not browser accessible.
I created an patch, https://github.com/CazYokoyama/ESP32-CAM_MJPEG2SD/pull/2
However, making the files in readable for all is a security risk. Is there any way to give read permission only for my devices?

**Comment by s60sc** [comment]
I can add a modified version of your patch in the next release as it only works for unix.

`Is there any way to give read permission only for my devices?`
You would need to create a suitable shell script on the ftp server.

**Comment by CazYokoyama** [comment]
This is implemented by
local_umask=022
on vsftpd.conf. No need to modify ESP32-CAM_MJPEG2SD. Thank you anyway.
