### ISSUE TITLE
[Enhancement] Is it possible to add FTPS?

### ISSUE THREAD

**Issue by lztz0022** [s60sc/ESP32-CAM_MJPEG2SD#264]
Sir s60sc, 
The project feature has been stable since 8.7.1a. I also see that the focus of your work is mainly shifted to the adaptation of ESP32S3.
Now I have a kind request for functional enhancement: many FTP service provider no longer provides pure FTP protocol, they think that plaintext transmission is too insecure, so they are now using FTP+TLS/SSL Explicit encryption. I learned that the ftplibpp library can be implemented, but it is too redundant. So, is it possible to implement TLS/SSL Explicit encryption enhancements based on the current FTP? Thank you and best regards.

**Comment by s60sc** [comment]
it would require research which would not occur in the short term

**Comment by s60sc** [comment]
tried, not successful

**Comment by lztz0022** [comment]
It's regrettable, but thank you very much for trying.
