### ISSUE TITLE
Por Forward

### ISSUE THREAD

**Issue by YaphethSN** [s60sc/ESP32-CAM_MJPEG2SD#269]
hello there! i would like to know how to use this code and port forward using my router only if that is possible, the code is working but im not sure how to port forward? if you could explain it or give a tutorial that would be magnificent, and im using a zte f609 router and not sure how to convert the lan to wan, sorry if im a bit slow

**Comment by YaphethSN** [comment]
[]
![Screenshot 2023-09-09 213243](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/144543905/0f3eb233-f170-4ce2-89c2-c88afadab0cd)
(url)

heres what the port forward looks like in my router
doesnt match up with yours

**Comment by s60sc** [comment]
https://www.cfos.de/en/cfos-personal-net/port-forwarding/zte-f609.htm
But dont use 80 for wan port

**Comment by YaphethSN** [comment]
> https://www.cfos.de/en/cfos-personal-net/port-forwarding/zte-f609.htm But dont use 80 for wan port

what should i do then?

**Comment by YaphethSN** [comment]
my main problem is the wan host star and end ip address, as i placed in the ip from whats my ip and it doesnt work
![Screenshot 2023-09-10 093101](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/144543905/4ec8ba17-041b-4e8f-8404-fe56adac1e4d)
