### ISSUE TITLE
continuous recording instead of motion or force start

### ISSUE THREAD

**Issue by johnpiker** [s60sc/ESP32-CAM_MJPEG2SD#271]
What changes should I made to start the recording once I switch on the device. As I don't want to the motion dependency and force start through start button.
I disable the motion sense but how to activate the continuous monitoring without the start on button. Can I hard code it ?

As I want continuous recording of 30 min simultaneously.
Please help..

**Comment by s60sc** [comment]
in `mjpeg2sd.cpp`:
`forceRecord = true;` to start recording
`forceRecord = false;` to stop recording

**Comment by johnpiker** [comment]
Thankyou for this,
Just one more doubt as where should i keep the record duration do that it will automatically start and stop recording simultaneously after every 30 min.
As I wanted to record the 30 min clips round the clock simultaneously.

**Comment by s60sc** [comment]
`doAppPing() `in `appGlobals.cpp` is called every 30 secs, so put counter in that

**Comment by johnpiker** [comment]
We have some customised requirement of  audio and video recordings using ESP32 boards and uploading the recorded files on server using internet. If you can provide us the complete solution for our requirement we can freelance this project on payment basis. Please share your Email ID .

**Comment by johnpiker** [comment]
> doAppPing()

Thank you very much

**Comment by s60sc** [comment]
> We have some customised requirement of audio and video recordings using ESP32 boards and uploading the recorded files on server using internet. If you can provide us the complete solution for our requirement we can freelance this project on payment basis. Please share your Email ID .

Thanks, but I only code as a hobby for my own interest.

**Comment by johnpiker** [comment]
Sorry, and keep it on 👍

**Comment by johnpiker** [comment]
static bool closeAvi() {
  // closes the recorded file
  uint32_t vidDuration = millis() - startTime;
  uint32_t vidDurationSecs = lround(vidDuration/1000.0);
  logLine();
  LOG_DBG("Capture time %u, min seconds: %u ", vidDurationSecs, minSeconds);

  cTime = millis();
  // write remaining frame content to SD
  aviFile.write(iSDbuffer, highPoint); 
  size_t readLen = 0;
  // add wav file if exists
  finishAudio(true);
  bool haveWav = haveWavFile();
  if (haveWav) {
    do {
      readLen = writeWavFile(iSDbuffer, RAMSIZE);
      aviFile.write(iSDbuffer, readLen);
    } while (readLen > 0);
  }
  // save avi index
  finalizeAviIndex(frameCnt);
  do {
    readLen = writeAviIndex(iSDbuffer, RAMSIZE);
    if (readLen) aviFile.write(iSDbuffer, readLen);
  } while (readLen > 0);
  // save avi header at start of file
  float actualFPS = (1000.0f * (float)frameCnt) / ((float)vidDuration);
  uint8_t actualFPSint = (uint8_t)(lround(actualFPS));  
  xSemaphoreTake(aviMutex, portMAX_DELAY);
  buildAviHdr(actualFPSint, fsizePtr, frameCnt);
  xSemaphoreGive(aviMutex); 
  aviFile.seek(0, SeekSet); // start of file
  aviFile.write(aviHeader, AVI_HEADER_LEN); 
  aviFile.close();
  LOG_DBG("Final SD storage time %lu ms", millis() - cTime);
  uint32_t hTime = millis(); 
  if (vidDurationSecs >= minSeconds) {
    // name file to include actual dateTime, FPS, duration, and frame count
    int alen = snprintf(aviFileName, FILE_NAME_LEN - 1, "%s_%s_%u_%u_%u%s.%s", 
      partName, frameData[fsizePtr].frameSizeStr, actualFPSint, vidDurationSecs, frameCnt, haveWav ? "_S" : "", FILE_EXT);
    if (alen > FILE_NAME_LEN - 1) LOG_WRN("file name truncated");
    SD_MMC.rename(AVITEMP, aviFileName);
    LOG_DBG("AVI close time %lu ms", millis() - hTime); 
    cTime = millis() - cTime;
    // AVI stats
    LOG_INF("******** AVI recording stats ********");
    LOG_ALT("Recorded %s", aviFileName);
    LOG_INF("AVI duration: %u secs", vidDurationSecs);
    LOG_INF("Number of frames: %u", frameCnt);
    LOG_INF("Required FPS: %u", FPS);
    LOG_INF("Actual FPS: %0.1f", actualFPS);
    LOG_INF("File size: %0.2f MB", (float)vidSize / ONEMEG);
    if (frameCnt) {
      LOG_INF("Average frame length: %u bytes", vidSize / frameCnt);
      LOG_INF("Average frame monitoring time: %u ms", dTimeTot / frameCnt);
      LOG_INF("Average frame buffering time: %u ms", fTimeTot / frameCnt);
      LOG_INF("Average frame storage time: %u ms", wTimeTot / frameCnt);
    }
    LOG_INF("Average SD write speed: %u kB/s", ((vidSize / wTimeTot) * 1000) / 1024);
    LOG_INF("File open / completion times: %u ms / %u ms", oTime, cTime);
    LOG_INF("Busy: %u%%", std::min(100 * (wTimeTot + fTimeTot + dTimeTot + oTime + cTime) / vidDuration, (uint32_t)100));
    checkMemory();
    LOG_INF("*************************************");
    if (mqtt_active) {
      sprintf(jsonBuff, "{\"RECORD\":\"OFF\", \"TIME\":\"%s\"}", esp_log_system_timestamp());
      mqttPublish(jsonBuff);
    }
    if (autoUpload) ftpFileOrFolder(aviFileName); // Upload it to remote ftp server if requested
    checkFreeSpace();
    char subjectMsg[50];
    sprintf(subjectMsg, "Frame %u attached", smtpFrame);
    emailAlert("Motion Alert", subjectMsg);
    return true; 
  } else {
    // delete too small files if exist
    SD_MMC.remove(AVITEMP);
    LOG_INF("Insufficient capture duration: %u secs", vidDurationSecs); 
    return false;
  }
  **forceRecord = true;
  //doAppPing();
  //processFrame();
  openAvi();**
}

static boolean processFrame() {
  // get camera frame
  forceRecord = true;
  static bool wasCapturing = false;
  static bool wasRecording = false;
  static bool captureMotion = false;
  bool res = true;
  uint32_t dTime = millis();
  bool finishRecording = false;
  camera_fb_t* fb = esp_camera_fb_get();
  if (fb == NULL) return false;
  timeLapse(fb);
  // determine if time to monitor, then get motion capture status
  if (!forceRecord && useMotion) { 
    if (dbgMotion) checkMotion(fb, false); // check each frame for debug
    else if (doMonitor(isCapturing)) captureMotion = checkMotion(fb, isCapturing); // check 1 in N frames
  }
  if (pirUse) {
    pirVal = getPIRval();
    if (!pirVal && !isCapturing && !useMotion) checkMotion(fb, isCapturing); // to update light level
  }
  
  // either active PIR, Motion, or force start button will start capture, neither active will stop capture
  isCapturing = forceRecord | captureMotion | pirVal;
  if (forceRecord || wasRecording || doRecording) {
    if (forceRecord && !wasRecording) wasRecording = true;
    else if (!forceRecord && wasRecording) wasRecording = false;
    
    if (isCapturing && !wasCapturing) {
      // movement has occurred, start recording, and switch on lamp if night time
      if (lampAuto && nightTime) setLamp(lampLevel); // switch on lamp
      stopPlaying(); // terminate any playback
      stopPlayback = true; // stop any subsequent playback
      LOG_ALT("Capture started by %s%s%s", captureMotion ? "Motion " : "", pirVal ? "PIR" : "",forceRecord ? "Button" : "");
      if (mqtt_active) {
        sprintf(jsonBuff, "{\"RECORD\":\"ON\", \"TIME\":\"%s\"}", esp_log_system_timestamp());
        mqttPublish(jsonBuff);
      }
      openAvi();
      //counter
      
      wasCapturing = true;
    }
    if (isCapturing && wasCapturing) {
      // capture is ongoing
      dTimeTot += millis() - dTime;
      saveFrame(fb);
      showProgress();
      if (frameCnt >= maxFrames) {
        logLine();
        LOG_INF("Auto closed recording after %u frames", maxFrames);
        **forceRecord = false;
        finishRecording = true;**
      }
    }
    if (!isCapturing && wasCapturing) {
      // movement stopped
      finishRecording = true;
      if (lampAuto) setLamp(0); // switch off lamp
    }
    wasCapturing = isCapturing;
    LOG_DBG("============================");
  }
  if (fb != NULL) esp_camera_fb_return(fb);
  fb = NULL; 
  if (finishRecording) {
    // cleanly finish recording (normal or forced)
    
    if (stopPlayback) 
    Serial.println ("finish rec and stop playback");
    closeAvi();
    finishRecording = isCapturing = wasCapturing = stopPlayback = false; // allow for playbacks
  }
  return res;
}






I have done some changes in the process frame and close Avi in order to do the simlultaneous recording and i have given the timer as the number of frames as after certain numer of frames it should stop and save current recording and start new recording.


but the problem is that now i am not able to access the folder/file on the web page and not able to download them after connecting to ESP wifi.
can you help me with this

**Comment by s60sc** [comment]
what do the logs say

**Comment by johnpiker** [comment]
Nothing is showing on serial monitor while accessing the folder
![Screenshot 2023-10-05 181512](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/132565248/c4d6d157-e5f0-4c9b-9c49-5204139a4b41)
![WhatsApp Image 2023-10-05 at 18 14 30](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/132565248/56485741-9b19-470f-b953-80fc7ff0e954)
