### ISSUE TITLE
Error opening ftp connection to x.x.x.x:21 

### ISSUE THREAD

**Issue by Qyther** [s60sc/ESP32-CAM_MJPEG2SD#274]
Hello to all.

I have gotten this repo with its features to work quite well, and now I want to upload the recorded files to my FTP server. I have a server that is running on my home network with a working FTP server that I can connect with using my laptop, my PC, and my phone. I have the IP and everything set up correctly, the port is correct, the username and password are correct, and yet I can't seem to get it working.
This is what I get in the Serial Monitor/Log:

```
[03:18:10.901 ERROR @ ftp.cpp:71] Error opening ftp connection to x.x.x.x:21 
[03:18:10.902 ERROR @ ftp.cpp:183] Unable to make ftp connection
```

I have tried using ftp x.x.x.x in command line and gotten the following:
```
ftp x.x.x.x
Connected to x.x.x.x.
220 Microsoft FTP Service
200 OPTS UTF8 command successful - UTF8 encoding now ON.
User (x.x.x.x:(none)):
```

Besides all that, the ESP32-CAM has perfect internet connection, and its website can be accessed by all devices.

Looking forward to solving this with you. :)

**Comment by s60sc** [comment]
On web page `Motion Detect & Recording,` switch off `Motion detect` and `Save Capture`
On `Show Log` page switch on` Verbose`
This will show debug messages during FTP connection
