### ISSUE TITLE
Restart scheduler

### ISSUE THREAD

**Issue by DiBochev** [s60sc/ESP32-CAM_MJPEG2SD#277]
Hi all,
This software is great. The only issue is the crappy hardware, because it overheats and needs ALOT of heatsinks.
Can you create a restart scheduler policy: for example I want every day at 1:00 AM to restart the device?

Many thanks in advantage :)

**Comment by s60sc** [comment]
add following as first line in function `doAppPing() `in file `appSpecific.cpp`:

`  if (checkAlarm(1)) doRestart("User alarm"); // where 1 is 1am`

**Comment by lztz0022** [comment]
> add following as first line in function `doAppPing() `in file `appSpecific.cpp`:
> 
> ` if (checkAlarm(1)) doRestart("User alarm"); // where 1 is 1am`

What if it's 11:30 PM?

**Comment by DiBochev** [comment]
Thank you very much for the fast answer, but can this be made configurable using the web page?
For example restart every X hours (1, 2,3,.... 12) or restart at current time daily, weekly, monthly?
