### ISSUE TITLE
Two or more ESP32-CAM's without Router

### ISSUE THREAD

**Issue by Barx59** [s60sc/ESP32-CAM_MJPEG2SD#279]
Is it possible to access 2 or more ESP32-CAMs in an environment with no router present?

**Comment by s60sc** [comment]
Connect to each camera AP

**Comment by Barx59** [comment]
Thanks @s60sc . Presently, I do that successfully, ie. connecting to each AP, one at a time, but I'm hoping for a more streamlined solution which would save me connecting/disconnecting to AP's for access to each device ...... looking for a more streamlined solution, as it is with a router accessing multiple STA units via browser tabs. Maybe I need a generic AP between my phone and the ESP32-CAMs .... I really don't know, and welcome some direction?
