### ISSUE TITLE
FTP server Upload

### ISSUE THREAD

**Issue by bogdanys** [s60sc/ESP32-CAM_MJPEG2SD#28]
I can't upload file on ftp server. I keep receiving this error: Error opening ftp connection to ftp://192.168.36.137/:21.
I don't know if I'm doing something wrong. Could you help me please?

**Comment by s60sc** [comment]
There cannot be a / after the IP address

**Comment by bogdanys** [comment]
It still does not work. Maybe I'm setting the wrong configuration. The configuration is as follows:
The IP address from which I access the site is: 192.168.36.137
FTP Server: ftp://192.168.36.137:21
Ftp port: 21
Ftp username: test
Ftp password: test
Ftp root dir: /

**Comment by s60sc** [comment]
try connecting from windows command prompt to check ftp server

**Comment by bogdanys** [comment]
I did this and it displays Connection refused.

**Comment by s60sc** [comment]
then the problem is with your ftp server

**Comment by bogdanys** [comment]
But is strange because with other example the ftp server works perfectly.

**Comment by LeonardoZim** [comment]
I have the same problem

**Comment by s60sc** [comment]
i cant fix problems with peoples ftp server connections
