### ISSUE TITLE
OV5640 Camera heating

### ISSUE THREAD

**Issue by ltwin8** [s60sc/ESP32-CAM_MJPEG2SD#283]
I am using a XIAO with its upgraded ov5640 cam including autofocus ability.

the camera is getting very hot, you mentioned the supply voltage is too high, could you please tell me which supply voltage you refer to?

**Comment by s60sc** [comment]
From memory, all cam boards have external 1.2V and 2.8V LDO for OV2640, but OV5640 needs 1.5V instead of 1.2V so as there is no external 1.5V LDO it has to use the 2.8V supply and its internal 1.5V LDO.
