### ISSUE TITLE
Spaces in SSID are being dropped

### ISSUE THREAD

**Issue by dsldsl1980** [s60sc/ESP32-CAM_MJPEG2SD#285]
After the first reboot, I was able to log into the device from my laptop and set my wifi information.  

SSID: "The Comp-IOT"

After the reboot, I received an error on the serial monitor that said it couldn't connect

..[21:49:23.509 onWiFiEvent] Wifi AP stopped: ESP-CAM_MJPEG_E44F4F1B5AE0
[21:49:23.513 WARN startWifi] SSID TheComp-IOT unable to connect 
[21:49:23.514 onWiFiEvent] Wifi AP SSID: ESP-CAM_MJPEG_E44F4F1B5AE0 started, use 'http://192.168.4.1' to connect

After trying to reset the SSID a number of times I stood up a new network with the SSID it was looking for in the log "TheComp-IOT" and everything worked fine.  

Something is dropping spaces from the SSID that it tries to connect to

**Comment by s60sc** [comment]
In `appGlobals.h` change ALLOW_SPACES to true
