### ISSUE TITLE
Camera Tilt/Pan not saved Version 8.8

### ISSUE THREAD

**Issue by DiBochev** [s60sc/ESP32-CAM_MJPEG2SD#288]
Steps to reproduce:
1. open web ui using browser
2. 📷  Camera Control  
3. Change Tilt/Pan
4. Click Save Settings
4. Click Reboot ESP

Current result:
Missing props in config.txt
After restart, the servos are moved to position 90 disregard saved values
Web UI is pointing to position 90 for both

configs.txt
`
AP_Pass~~0~T~AP Password
AP_SSID~ESP-CAM_MJPEG_0CEB2D32A7B0~0~T~AP SSID name
AP_gw~~0~T~AP gateway
AP_ip~~0~T~AP IP Address if not 192.168.4.1
AP_sn~~0~T~AP subnet
Auth_Name~~99~~na
ST_SSID~******~99~~na
ST_gw~~0~T~Router IP address
ST_ip~~0~T~Static IP address
ST_ns1~~0~T~DNS server
ST_ns2~~0~T~Alt DNS server
ST_sn~255.255.255.0~0~T~Router subnet
ae_level~-2~98~~na
aec~1~98~~na
aec2~1~98~~na
aec_value~204~98~~na
agc~1~98~~na
agc_gain~0~98~~na
allowAP~1~0~C~Allow simultaneous AP 
appId~ESP-CAM_MJPEG~99~~na
autoUpload~0~98~~na
awb~1~98~~na
awb_gain~1~98~~na
bpc~1~98~~na
brightness~0~98~~na
cfgVer~2~99~T~na
colorbar~0~98~~na
contrast~0~98~~na
dcw~1~98~~na
deleteAfter~0~98~~na
denoise~4~98~~na
detectChangeThreshold~15~1~N~Pixel difference to indicate change
detectEndBand~8~1~N~Bottom band where motion is checked
detectMotionFrames~5~1~N~Num changed frames to start motion
detectNightFrames~10~1~N~Min dark frames to indicate night
detectNumBands~10~1~N~Total num of detection bands
detectStartBand~3~1~N~Top band where motion is checked
ds18b20Pin~~3~N~Pin used for DS18B20 temperature sensor
enableMotion~1~98~~na
formatIfMountFailed~0~2~C~Format file system on failure
fps~20~98~~na
framesize~9~98~~na
ftp_port~21~99~~na
ftp_server~~99~~na
ftp_user~~99~~na
ftp_wd~~99~~na
gainceiling~0~98~~na
hmirror~0~98~~na
hostName~ESP-CAM_MJPEG_0CEB2D32A7B0~99~~na
htmVer~4~99~T~na
jsVer~1~99~T~na
lampLevel~0~98~~na
lampPin~4~3~N~Pin used for Lamp
lampType~0~3~S:Manual:PIR~How lamp activated
lampUse~1~3~C~Use lamp
lenc~1~98~~na
logMode~0~99~~na
lswitch~20~98~~na
maxFrames~20000~1~N~Max frames in recording
micGain~0~98~~na
micSWsPin~~3~N~Microphone I2S WS / PDM CLK pin
micSckPin~~3~N~Microphone I2S SCK pin
micSdPin~~3~N~Microphone I2S SD / PDM DAT pin
micUse~0~3~C~Use microphone
minf~5~98~~na
motionVal~8~98~~na
moveStartChecks~5~1~N~Checks per second for start motion
moveStopSecs~2~1~N~Non movement to stop recording (secs)
mqtt_active~0~2~C~Mqtt enabled
mqtt_broker~~2~T~Mqtt server ip to connect
mqtt_port~1883~2~N~Mqtt server port
mqtt_topic_prefix~homeassistant/sensor/~2~T~Mqtt topic path prefix
mqtt_user~~2~T~Mqtt user name
mqtt_user_Pass~~2~T~Mqtt user password
ntpServer~pool.ntp.org~0~T~NTP Server address
pirPin~~3~N~Pin used for PIR
pirUse~0~3~C~Use PIR for detection
quality~12~98~~na
raw_gma~1~98~~na
record~1~98~~na
refreshVal~5~2~N~Web page refresh rate (secs)
responseTimeoutSecs~10~2~N~FTP / SMTP response timeout (secs)
restart~~99~~na
saturation~0~98~~na
sdFreeSpaceMode~1~2~S:No Check:Delete oldest:Ftp then delete~Action mode on SD min free
sdMinCardFreeSpace~100~2~N~Min free MBytes on SD before action
servoDelay~0~3~N~Delay between each 1 degree change (ms)
servoMaxAngle~180~3~N~Set max angle for servo model
servoMaxPulseWidth~2400~3~N~Set max pulse width for servo model (usecs)
servoMinAngle~0~3~N~Set min angle for servo model
servoMinPulseWidth~544~3~N~Set min pulse width for servo model (usecs)
servoPanPin~3~3~N~Pin used for Pan Servo
servoTiltPin~1~3~N~Pin used for Tilt Servo
servoUse~1~3~C~Use servos
sharpness~0~98~~na
smtpFrame~5~2~N~Frame number image sent in email
smtpMaxEmails~10~2~N~Max daily emails
smtpUse~0~2~C~Enable email sending
smtp_email~~99~~na
smtp_login~~99~~na
smtp_port~465~99~~na
smtp_server~smtp.gmail.com~99~~na
special_effect~0~98~~na
teleInterval~1~3~N~Telemetry collection interval (secs)
teleUse~0~3~C~Use telemetry recording
timeLapseOn~0~98~~na
timezone~GMT0~98~~na
tlDurationMins~720~1~N~Timelapse duration (mins)
tlPlaybackFPS~1~1~N~Timelapse playback FPS
tlSecsBetweenFrames~600~1~N~Timelapse interval (secs)
uartRxdPin~~3~N~UART1 RX pin
uartTxdPin~~3~N~UART1 TX pin
useIOextender~0~3~C~Use another ESP as IO Extender
usePing~1~0~C~Use ping
useUART0~0~99~C~na
vflip~0~98~~na
voltDivider~2~3~N~Voltage divider resistor ratio
voltInterval~5~3~N~Voltage check interval (mins)
voltLow~3~3~N~Warning level for low voltage
voltPin~~3~N~ADC Pin used for battery voltage
voltUse~0~3~C~Use Voltage check
wakePin~~3~N~Pin used for to wake app from sleep
wakeUse~0~3~C~Deep sleep app during night
wb_mode~0~98~~na
wifiTimeoutSecs~30~0~N~WiFi connect timeout (secs)
wpc~1~98~~na
xclkMhz~20~98~~na`

**Comment by s60sc** [comment]
not saved by design

**Comment by DiBochev** [comment]
thank you :)
