### ISSUE TITLE
Freenove esp32s3 wroom 

### ISSUE THREAD

**Issue by CFtonic** [s60sc/ESP32-CAM_MJPEG2SD#290]
Can you tell me what available pins to use for the I2S mic please?

**Comment by s60sc** [comment]
see readme

**Comment by CFtonic** [comment]
Obviously already read the readme. Free pins im using are pin 41 - mic WS, pin 42 mic SCK, pin 47 mic SD.
Mic doesnot work using free pins as suggested in readme. I expect that you have mic connected to your esp32s3 setup and you just look and tell me what pin config you are using.
