### ISSUE TITLE
No lamp when using servos Version 8.8

### ISSUE THREAD

**Issue by DiBochev** [s60sc/ESP32-CAM_MJPEG2SD#291]
use pins 1 and 3 for servos 
enable lamp
try to turn the lamp on max 

Current result: 
the lamp turns on about 5 %
the lamp should turn on on 100%

also there is some gibberish non-stop logging
![image](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/7621587/ea01d8a3-2029-44f5-98be-582b8f7605dd)

disable servos
turn lamp on 100%
lamp turns on 100%

if the pins for the servos i am using are not correct, please advise the correct ones

**Comment by s60sc** [comment]
cant use pin 1. see readme
