### ISSUE TITLE
test section exceeds available space in board

### ISSUE THREAD

**Issue by CashOlsen** [s60sc/ESP32-CAM_MJPEG2SD#296]
Sketch uses 1480373 bytes (112%) of program storage space. Maximum is 1310720 bytes.

i'm using Arduino IDE 2.2.1
esp32 by Espressif version 2.0.14

ESP32S3 Dev Module Freenove WROOM-1 OV2640

ESP-CAM_MJPEG2SD Version 9.0 no modifications to any file

Compiled for target AI Thinker with no trouble

**Comment by s60sc** [comment]
see [readme](https://github.com/s60sc/ESP32-CAM_MJPEG2SD#:~:text=Select%20the%20ESP32,8M%20with%20spiffs%20(...))
