### ISSUE TITLE
Core 1 panic'ed on esp32-cam

### ISSUE THREAD

**Issue by YummyFatPeanut** [s60sc/ESP32-CAM_MJPEG2SD#297]
On pressing the record button in station mode, the camera (OV2640) immediately resets with a core panic error. 
`16:52:33.482 -> [12:52:33.475 processFrame] Capture started by Button 
16:52:33.515 -> Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.`
Using a 64 gb sd card, the camera saves all configs and logs. ResetReason is-
`12:52:35.157 printResetReason] Software reset due to exception/panic
[12:52:35.157 printWakeupReason] Wakeup by reset`

**Comment by s60sc** [comment]
Need to [decode stack trace](https://github.com/s60sc/EspCrashDecoder)
try a smaller card, only cards up to 32gb supported by mmc library

**Comment by YummyFatPeanut** [comment]
I have tried an 8 gb card, didn't work.
Now trying to decode trace
