### ISSUE TITLE
Esp32-cam no AP but OK after reset

### ISSUE THREAD

**Issue by armand2011** [s60sc/ESP32-CAM_MJPEG2SD#299]
Just some issues I want to share;

Initial test I had the camera away from the SD Card holder which acts as a heatsink, this caused the camera to overheat and thus go into some kind of power down or sleep mode. So take some heatsink paste and paste it down on the SD Card case.

I have my camera on a solar light so it's regular is not the best, what seems to be happening is that the battery would run down, causing the BMS to switch everything off in the early morning hours, when the sun comes up it switched back on but it doesn't seem to have enough power, so looks like the limited current would cause the unit to fail in loading the AP and Wifi etc parameters.

It still runs, but there is no AP and no Wifi interface, a reset would solve the problem, obviously because by the time I do a reset the battery now has enough power.

My simple solution was to delay the startup by 15 minutes, this gives the solar panel enough time to put some power in the battery.

I suppose the code could be modified to allow for this but a better solution would be a better setup, and maybe a battery monitoring system to delay the startup until the battery has at least some charge.

To simulate this fault simple connect the unit to a variable power supply with a adjustable current limit, adjust the voltage to 5V and the current limit to 0mA, now very slowly increase the current unit you see the unit trying to power up, the current limit will now prevent it from powering up properly.

Hope this helps

**Comment by s60sc** [comment]
wifi needs a lot of power, so it will brownout when trying to start wifi.
