### ISSUE TITLE
SD delet

### ISSUE THREAD

**Issue by burkadius** [s60sc/ESP32-CAM_MJPEG2SD#3]
Hello, I implemented the project and was surprised how powerful the ESP32 cam is. I've been testing the application for a few days now and noticed that recording stops when the SD memory card is full. I had thought that when the memory capacity is reached, the oldest files will be overwritten. Can you tell me what is correct : 1. memory card full means end of recording until manual deletion. 
OR
2. the memory card should be automatically overwritten when it is full.

I'am using the ESP32-cam motion variant
Best regards
Burkhard

**Comment by s60sc** [comment]
The code is not intended as a complete project but as a utility to add to a user's own project. So would need to write your own code to handle when SD card full.
