### ISSUE TITLE
Web server unaccessible (urgent!)

### ISSUE THREAD

**Issue by Creaminal27** [s60sc/ESP32-CAM_MJPEG2SD#300]
![photo_2023-11-17_00-13-12](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/151057863/9d15eddc-bf52-461d-99e3-25d96e93a911)
i did everything as the guide says but i can't access the web server, it only shows that, but the camera is working as it it intended, i just can't view it. Please help me as i need to present the project by next week ;(

**Comment by s60sc** [comment]
its waiting for you to enter your router ssid and password, so it can download the data folder.
If you only want to use AP, use OTA Update button to store the data folder contents manually.
