### ISSUE TITLE
Can't start stream on ESP32 AI_Thinker_CAM module 

### ISSUE THREAD

**Issue by Minha-D** [s60sc/ESP32-CAM_MJPEG2SD#302]
Hi, First of all,Thanks for creating such a amazing project.
I have a problem with starting camera stream on browser. When Start stream is clicked video window remains black. Capturing sills work and they show the preview. And recording on sdcard is also working. But live stream isn't working and sometimes it says something like "not enough free space with error code 500"
I'm using version 9.1 on esp32_cam ai_thinker_board. Any help is appreciated.

**Comment by s60sc** [comment]
Need to see log and exact message - is it `500: No free task`

**Comment by Minha-D** [comment]
> Need to see log and exact message - is it `500: No free task`

Yes is it "500: No Free Space".
But version 8.7 is working.

**Comment by Minha-D** [comment]
I'll attach logs then, to verify what's the problem.

**Comment by Minha-D** [comment]
Here is the log from sdcard : [log.txt](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/files/13403299/log.txt)
Here is the screen short of my browser  ![Screenshot_20231119_192152](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/81606055/153f54e1-69b9-4c0c-97d9-d82dff0b48f7)
![Screenshot_20231119_192227](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/81606055/caac9c3a-d328-48ce-af25-fbec17c8a732)

**Comment by s60sc** [comment]
No idea. Check you have no other browser instances open, [try chrome browser](https://github.com/s60sc/ESP32-CAM_MJPEG2SD#:~:text=Browser%20functions%20only%20tested%20on%20Chrome.), or use an older release.

**Comment by Minha-D** [comment]
I maked sure no other browsers are open. And also if you looked at the screenshot I'm using Google Chrome only. Thanks for the response I'll use older 8.7 version for now.
