### ISSUE TITLE
Unable to start stream on browser

### ISSUE THREAD

**Issue by TNGop** [s60sc/ESP32-CAM_MJPEG2SD#303]
![Screenshot_20231119-183456](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/102600195/0a514e00-415c-4ba2-95d5-d3cfe6332eb5)

I have same like Minha-D but in my case it does not show any log like 500: No free task . In my case it shows (ERROR @ utils.cpp:347] Timed out connecting to server: api.ipify.org, Err: ERROR Generic error)
You can check screenshot 
![Screenshot_20231119-133504](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/102600195/a2de4f5e-e13b-4f7b-86ab-8c455f0a32e5)

![Screenshot_20231119-134311](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/102600195/1e5a494e-04c1-4f88-921e-49ea9adea22b)

**Comment by s60sc** [comment]
that error can be ignored as not connected to internet

**Comment by TNGop** [comment]
What about starting stream on browser

**Comment by s60sc** [comment]
No idea, try an older release.
