### ISSUE TITLE
SD card mount failed 

### ISSUE THREAD

**Issue by frtug** [s60sc/ESP32-CAM_MJPEG2SD#304]
I upload the code in my esp32 and i connected the eps32 wifi signal to run webserver then i am getting sd mount failed.
![Screenshot 2023-11-21 at 23 57 31](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/32640258/7852f8b4-b56c-406e-b195-5501d2b1da48)

This is the error msg.

**Comment by s60sc** [comment]
hardware problem

**Comment by frtug** [comment]
Do i need to replace the sd card slot ?
One more thing which format of sd card we need?
