### ISSUE TITLE
v9.1 gives few errors

### ISSUE THREAD

**Issue by dr-garimella** [s60sc/ESP32-CAM_MJPEG2SD#306]
![WhatsApp Image 2023-11-21 at 2 58 34 PM](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/147712432/2ef88f0a-312b-4e3a-940c-e04500a6b4c8)

Kindly, help /  guide. Not able to stream.

**Comment by s60sc** [comment]
task already being used to stream / playback / download.
I'll be making a change that new requests will close older requests to free the task

**Comment by s60sc** [comment]
v9.1.2
