### ISSUE TITLE
Cannot get it to connect to wifi

### ISSUE THREAD

**Issue by C4PT41ND34DP00L** [s60sc/ESP32-CAM_MJPEG2SD#31]
I am trying this sketch but I cannot get it to connect to wifi and not sure why. It uploads just fine

**Comment by C4PT41ND34DP00L** [comment]
So it seems to be unable to mount the SD Card

**Comment by C4PT41ND34DP00L** [comment]
Turns out once I fixed my serial monitor I was able to find that t was the SD card type was wrong.

**Comment by s60sc** [comment]
Thanks for providing a closure

**Comment by C4PT41ND34DP00L** [comment]
> Thanks for providing a closure

Was a real facepalm moment when I saw the issue.
