### ISSUE TITLE
About battery 

### ISSUE THREAD

**Issue by TNGop** [s60sc/ESP32-CAM_MJPEG2SD#310]
On which pins should I attach battery.I don't have any ideas.Please mark here in this picture 
![ESP32-CAM-pinouts](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/102600195/de93c366-0cc1-40a2-b876-219664312301)

**Comment by TNGop** [comment]
4v battery

**Comment by s60sc** [comment]
none
