### ISSUE TITLE
motion detection doesn't trigger the recording

### ISSUE THREAD

**Issue by TheWarimin** [s60sc/ESP32-CAM_MJPEG2SD#311]
I tried to establish the static IP which did not work so I took out the SD card and deleted the static IP configuration and the router's IP and for some reason the motion detection does not trigger the recording, I reinstalled everything from scratch and the motion detection still does not trigger recording

**Comment by s60sc** [comment]
impossible for me to diagnose

**Comment by TheWarimin** [comment]
understandable, I really like the project and I hope it continues, thanks for your time.
