### ISSUE TITLE
Unable to download longer recordings

### ISSUE THREAD

**Issue by Shadowpost** [s60sc/ESP32-CAM_MJPEG2SD#314]
Files over 6MB cannot be downloaded. The download simply stops half way and if you resume it, it will begin at 0.

I do have: "ERROR utils@cpp:323 No External IP returned" popping up every 30 seconds or so in the web browser. Everytime that pops up, the download fails.
I tried to open some ports on my router, but i can't find which port is used by my camera. Forwarding ports 80 and 10880 doesn't fix the problem.

Any help is appreciated, since I hope to use the telegram bot as well.

**Comment by s60sc** [comment]
You have a bad network connection
