### ISSUE TITLE
v9.1.2 streaming black screen issue

### ISSUE THREAD

**Issue by dr-garimella** [s60sc/ESP32-CAM_MJPEG2SD#317]
![lOG](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/147712432/91a8601f-bc38-48cd-9d29-45b388e00d7e)
![No Stream](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/147712432/e2e0db23-3127-462b-8c9b-02a1d9df7257)

Not Streaming the video. Only black screen for any resolution.

_Please, do the needful.!_

**Comment by s60sc** [comment]
No idea how to do the needful
