### ISSUE TITLE
No camera data received. 

### ISSUE THREAD

**Issue by Sommerbo** [s60sc/ESP32-CAM_MJPEG2SD#319]
Streaming and stills produce no image. Related to #317  but I tried to supply a bit more information.

Running on v 9.1.2 
Using generic ESP-CAM/AI Thinker camera.
I left all the default settings in "appGlobals.h"

Streaming never works and the log reports 0 frames. Taking a "Still" report an error
[10:00:40.911 ERROR @ appSpecific.cpp:218] Failed to get still
[10:00:58.501 showStream] MJPEG: 0 frames, total 0 bytes in 10.8s @ 0.0fps

Peeking at the code around 218, it looks like the image buffer is empty.

Verbose logging reveals that motion detect is working as it see varying amounts of differences when I wave in front of the camera.

The camera works, I got ESPHome/Homeassistant to show pictures but it was horrifically slow.

Feel free to ask for clarification to help resolve this.

**Comment by s60sc** [comment]
As cannot reproduce issue, have no idea. Does record / playback work

**Comment by s60sc** [comment]
streaming doesnt use sd
i've not had issues with aliexpress cams, but try reducing clock speed to 10mhz in picture settings

**Comment by Sommerbo** [comment]
I switched SD card, now recording and playback works. 

Still no streaming or stills.
I reduced clock speed to 10 Mhz Both on 9.1.2 and 9.2 no difference.

**Comment by Sommerbo** [comment]
To be clear, I don't expect miracles, troubleshooting an issue you can't reproduce is very hard. I would like to thank you for the time you are putting in.

**Comment by s60sc** [comment]
as per #320 check your wifi connection strength

**Comment by Sommerbo** [comment]
[12:20:57.534 startWifi] Wifi stats for ASUS - signal strength: -81 dBm; My computer is on a wired network.

Reducing recording size to 160x120 still refused to stream, while record and playback worked fine. If record and playback works, it seems less likely to be a bandwidth issue. 
Equally the LED control not functioning would seem unconnected to bandwidth.
 And finally saving stills, is that impacted by bandwidth? I assumed it just grabbed the current jpg.

**Comment by s60sc** [comment]
use your browser inspector ctrl-shft-i. try [wireshark](https://www.wireshark.org/download.html).
