### ISSUE TITLE
Feature Request: Multiple ESP32-CAMs Support 

### ISSUE THREAD

**Issue by Suraj-Sangwan** [s60sc/ESP32-CAM_MJPEG2SD#322]
It would be really great if you could add the support of video streams from multiple ESP32-CAMs which can be accessed on the same page at once using the same static ip.

**Comment by s60sc** [comment]
see this [fork](https://github.com/gemi254/ESP32-CAM_MJPEG2SD)

**Comment by Suraj-Sangwan** [comment]
Thanks for the help buddy.
