### ISSUE TITLE
Compilation error: 'esp_ping_handle_t' does not name a type; did you mean 'esp_eth_handle_t'?

### ISSUE THREAD

**Issue by EletrixtimeYT** [s60sc/ESP32-CAM_MJPEG2SD#328]
Hello i have this error :

Compilation error: 'esp_ping_handle_t' does not name a type; did you mean 'esp_eth_handle_t'?

**Comment by s60sc** [comment]
see [readme](https://github.com/s60sc/ESP32-CAM_MJPEG2SD#:~:text=NOTE%3A%20If%20you%20get%20compilation%20errors%20you%20need%20to%20update%20your%20arduino%2Desp32%20library%20in%20the%20IDE%20using%20Boards%20Manager)
