### ISSUE TITLE
Telegram not working

### ISSUE THREAD

**Issue by random-strings** [s60sc/ESP32-CAM_MJPEG2SD#330]
Hi, i installed version 9.3 on esp3s3 xiao sense and i'm getting the following error in the logs when video capture is started. Please help.

**[01:00:22.303 ERROR @ utils.cpp:356] Timed out connecting to server: api.telegram.org, Err: �V@��?�����)�7@T��?"�7@��?**  
**[01:00:37.404 ERROR @ telegram.cpp:210] Failed to communicate with Telegram server**

**Comment by s60sc** [comment]
cant help with external connectivity, maybe your telegram credentials are not recognised

**Comment by random-strings** [comment]
I tried to connect from my home ISP, and a mobile internet hotspot, and so far no luck only the error message has changed a little bit, the gibberish characters have disappeared.
**[12:51:07.630 ERROR @ utils.cpp:356] Timed out connecting to server: api.telegram.org, Err: #**  
**[12:51:22.631 ERROR @ telegram.cpp:210] Failed to communicate with Telegram server**

I don't know if the other issue I encounter - that the time is not displayed correctly is related to the telegram issue.
