### ISSUE TITLE
The time is wrong

### ISSUE THREAD

**Issue by random-strings** [s60sc/ESP32-CAM_MJPEG2SD#331]
I am running the software on xiao sense esp32s3 version of software 9.3.
This issue I also encountered on esp32cam board software version 9.1.
So the issue is that the system time indicated in windows and the time which is indicated by the ESP32-CAM_MJPEG2SD in the control panel is out of sync for an odd number of minutes.
I don't know why this happens, any ideas or similar expiriences?

bellow are logs that show that time was pulled but it is wrong(out of sync) with the hour on all my other devices.

[11:40:37.256 resetWatchDog] WatchDog started using task: ping  
[11:40:37.257 getLocalNTP] Using NTP server: pool.ntp.org  
[13:40:37.257 showLocalTime] Got current time from NTP: 05/01/2024 13:40:37 with tz: <+02>-2

![time divergence](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/155646191/9cb62417-6f31-446b-83a5-5cb49c67d492)
![Screenshot 2024-01-05 at 13-07-05 ESP-CAM_MJPEG_DCF917F93030](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/155646191/b8ffd74f-615c-4484-8aa1-501f49d09f64)

**Comment by gary-justausername** [comment]
Hi, I use GMT +0 and mostly 18 minutes fast! Very occasionally correct.

**Comment by random-strings** [comment]
> Hi, I use GMT +0 and mostly 18 minutes fast! Very occasionally correct. Bizarre the 18 minutes

Are telegram notifications working for you?

**Comment by gary-justausername** [comment]
Sorry I've not tested that yet. I've just finished pan/tilt servos on GPIO1 and GPIO3. Are you having problems with the telegram notifications that I might run into?
