### ISSUE TITLE
Is there a lightweight video & sound recording version?

### ISSUE THREAD

**Issue by pinter75** [s60sc/ESP32-CAM_MJPEG2SD#341]
Hi,

Wow, this is very featured! kudos!

I have it running on a ESP32S3 XIAO Sense perfectly.

Just a quick version, is there a light weight code base that does basic video & audio recording to SD card? While all the features added are fantastic, having a basic video record code base would be great to use in projects.

**Comment by s60sc** [comment]
I may look at adding defines so that unwanted cpp files can be deleted

**Comment by pinter75** [comment]
That would be very useful!

**Comment by KaliAssistant** [comment]
Same

**Comment by s60sc** [comment]
see v9.5
