### ISSUE TITLE
Startup Failure: Check SD card inserted.

### ISSUE THREAD

**Issue by aviatorhh** [s60sc/ESP32-CAM_MJPEG2SD#342]
I have an ESP32-CAM board running and configured as CAMERA_MODEL_AI_THINKER. It runs fine for some time but after some hours the camera becomes unresponsive and after a few restarts it is ok again. The SD card is a SanDisk and not old. In the meantime I get the failure message in the browser as titled.
Any clues?

**Comment by s60sc** [comment]
may be hardware problem eg overheating

**Comment by aviatorhh** [comment]
You may be right, but I think it is more because of lower temps around freezing here. The cam observes a birdhouse.

**Comment by s60sc** [comment]
i have outside cams in clear plastic enclosures that keep them warm enough
