### ISSUE TITLE
I need to turn on automatic recording start

### ISSUE THREAD

**Issue by mehmetcm7** [s60sc/ESP32-CAM_MJPEG2SD#344]
Hello , I'm using the ESP32-CAM_MJPEG2SD 9.3 code for my project. I've disabled the motion detection feature, but I need to automatically record video to the SD card from the moment the ESP32 starts working. Can you help me with how to achieve this? This is crucial for me.

**Comment by s60sc** [comment]
try define a pir pin, keep it high

**Comment by mehmetcm7** [comment]
Can we change this with code or add it somehow?

**Comment by s60sc** [comment]
its a setting - see [readme](https://github.com/s60sc/ESP32-CAM_MJPEG2SD#:~:text=Configuration%20Web%20Page,camera%20motion%20detection)
