### ISSUE TITLE
no ap mode or not local ip opening

### ISSUE THREAD

**Issue by DJprasenjit** [s60sc/ESP32-CAM_MJPEG2SD#345]
i clicked use https and saved and reboot after that . may local static ip not opening or i connect ap mode and open 192.168.4.1 but not opening

**Comment by s60sc** [comment]
Start URL with https://

**Comment by DJprasenjit** [comment]
https://192.168.0.177 not opening with https also. what to do, how to disable use https

**Comment by s60sc** [comment]
Did you create certificates for 192.168.0.177? 
Did you read the instructions?
To disable https delete the configs.txt file.

**Comment by DJprasenjit** [comment]
ok, i deleted config now only using http. but telegram bot is not working, error not enough memory, in 9.5

**Comment by s60sc** [comment]
I can't fix your memory problems, use an S3

**Comment by Nurullah6513** [comment]
Wifi ismi geliyor bağlanıyorum internet erişimi yok diyor ve verdi ip adreste açılmıyor hata alıyorum sürekli yardımcı olur musunuz
