### ISSUE TITLE
Correct RAMSIZE for 16gb SD card

### ISSUE THREAD

**Issue by amansinghaljpr** [s60sc/ESP32-CAM_MJPEG2SD#35]
Hey first of all amazing job man ! Your work can actually be used as a CCTV camera or a portable handheld camera by people .

Coming to the question i am using a 16GB microsd card so what will be the correct RAMSIZE value for it ?

**Comment by s60sc** [comment]
Thanks
Unless your card uses a blocksize that is not a multiple of 512 you can leave it as is

**Comment by amansinghaljpr** [comment]
> Thanks
> Unless your card uses a blocksize that is not a multiple of 512 you can leave it as is

Understood ! Thanks
