### ISSUE TITLE
Lamp activate on motion 

### ISSUE THREAD

**Issue by sjude68** [s60sc/ESP32-CAM_MJPEG2SD#351]
This is not a issue but a request. 

Can lamp be activated on motion instead of PIR. I am using Esp32-cam. I want the built-in led to come on and record video.

**Comment by s60sc** [comment]
motion wont work in dark, so lamp would have to be on beforehand

**Comment by sjude68** [comment]
I get the recording started on motion but when the person comes closer the face cannot be seen because the light is less.

I have used the Esp32-cam on my door.
