### ISSUE TITLE
No serial data received

### ISSUE THREAD

**Issue by soyabeannnn** [s60sc/ESP32-CAM_MJPEG2SD#353]
A fatal error occurred: Failed to connect to ESP32: No serial data received.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html
Failed uploading: uploading error: exit status 2

Model: ESP 32 CAM and FTDI

**Comment by s60sc** [comment]
As the troubleshooting states, you have a hardware problem with your FTDI device
