### ISSUE TITLE
Camera fails to download /data/config.txt, because it was removed from github repository

### ISSUE THREAD

**Issue by StupidProgramming** [s60sc/ESP32-CAM_MJPEG2SD#358]
Hi, 

I get the following error:
[14:53:50.039 wgetFile] Downloading /data/configs.txt from /s60sc/ESP32-CAM_MJPEG2SD/master/data/configs.txt
[14:53:50.286 ERROR @ setupAssist.cpp:39] Download failed, error:
[14:53:50.292 ERROR @ setupAssist.cpp:46] HTTP Get failed with code: 404

and when i check, i see the configs.txt file has been removed form the repository 2 weeks ago.

![image](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/92435626/cc283913-4fe4-4bc1-9f94-2b0877d92739)

Can you please put the file back?

**Comment by s60sc** [comment]
either use latest release or get file from older release

**Comment by StupidProgramming** [comment]
Okay, but it doesn't hurt to keep older versions working right?

**Comment by rjsachse** [comment]
> Okay, but it doesn't hurt to keep older versions working right?

I don't understand the reason to keep older versions working for a non commercial project. best bet if having issues upload to latest version or make a pr with changes
