### ISSUE TITLE
WIFI Network settings / SSID name issue

### ISSUE THREAD

**Issue by coph** [s60sc/ESP32-CAM_MJPEG2SD#359]
It looks like the device cannot connect to a network if the SSID contains space char.
I've tried couple of names. If SSID name does not contain space char - it connect without issue. 
The log removes the spaces. I guess some part of the code removes the spaces too when trying to connect to WIFI.

I'm using **"The girl next door"** as SSID name which is not working, Log is showing cannot connect on **"Thegirlnextdoor"**.
If I'm using **"Aime-moi!"** as SSID it connects to WIFI.

Thanks for the good work.
Paul

**Comment by s60sc** [comment]
in `appGlobals.h` set `ALLOW_SPACES `to `true`
