### ISSUE TITLE
Assigning Ip address

### ISSUE THREAD

**Issue by Shashwatraj3951** [s60sc/ESP32-CAM_MJPEG2SD#36]
Hello sir,
This project is running very nice.
But I have two following questions:-

1. When I am connecting with my wifi (Jio Fiber) for the first time it displays IP but after restart of the device, it gives another IP. So, I want static IP how can I do this in code??

2. I want to see its output over the internet. So, I am using ngrok but it displays "headers are too long to handle" .
How can I use it over the internet any suggestions or tools?

Please reply sir very important...
Thanks!

**Comment by s60sc** [comment]
1. In ```myconfig.h``` assign value for

```char ST_ip[16]  = ""; //Static IP```

and fill in other ```ST_*``` values

2. I do not know ngrok
