### ISSUE TITLE
[FEATURE REQUEST]  Audio Streaming

### ISSUE THREAD

**Issue by rjsachse** [s60sc/ESP32-CAM_MJPEG2SD#360]
hello, have you looked at audio streaming too? this project streams audio and video and sync together with go2rtc [ESP32-CAM_Audio](https://github.com/spawn451/ESP32-CAM_Audio)

**Comment by rjsachse** [comment]
That would be good. Then can stream to homeassistant and save to sd card.

**Comment by s60sc** [comment]
v9.6 released
