### ISSUE TITLE
PSRAM issue

### ISSUE THREAD

**Issue by DJprasenjit** [s60sc/ESP32-CAM_MJPEG2SD#362]
i have a old esp32 cam module which one works perfect with this, and PSRAM free 1.4MB 
![image](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/108330279/78063e62-c592-4294-9230-612dd993bc27)

But i bought some new esp32cam modules there i uploaded this same code but PSRAM free only 300-400KB why is this happening?
is these new modules i baught are Duplicate cam module?
![image](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/108330279/6ac05564-92bd-4f16-bcf8-f4aee8b0ba3d)

**Comment by s60sc** [comment]
Not an app issue
