### ISSUE TITLE
Camera init error 0xffffffff

### ISSUE THREAD

**Issue by InokentiySSL** [s60sc/ESP32-CAM_MJPEG2SD#363]
I bought 2 camera models and get the same error. The standard example from arduino ide works and the camera shows. Why is that?
![Снимок экрана 2024-02-07 153531](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/112630164/50592221-3f09-49dd-a0c0-ea1ee4b3eb30)
![Снимок экрана 2024-02-07 152507](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/112630164/d0fad4a5-6395-4544-a829-8541a91b9d23)
![photo_2024-02-08_13-22-20](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/112630164/45aec217-c23e-49f9-8cfc-4f89911c1286)

**Comment by InokentiySSL** [comment]
This project is also working.
https://github.com/easytarget/esp32-cam-webserver
![Снимок экрана 2024-02-08 140912](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/112630164/800ebe15-3eda-43a9-8b14-c7c1bb90cf43)
![Снимок экрана 2024-02-08 140934](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/112630164/f144033f-60f1-4b25-a9f4-652f8469e422)

**Comment by s60sc** [comment]
in `ESP32-CAM_MJPEG2SD.ino `replace:

`  if (psramFound()) prepCam();`

with:

```
  if (psramFound()) {
    LOG_INF("PSRAM size: %s", fmtSize(esp_spiram_get_size()));
    prepCam();
  }
```

Need at least 4MB PSRAM

**Comment by nelsonvarela** [comment]
I think this issue can be closed. My CAM has 2MB PSRAM but the seller has 4MPSRAM stated on the website.... misinformation!

I can also see in @InokentiySSL's screenshot he has 2095071 bytes which is not enough.

Thanks @s60sc for your patience and willing to help.

**Comment by s60sc** [comment]
Thanks for that useful information.  I'll add a note to the readme

**Comment by soyabeannnn** [comment]
But the thing is I've used different boards from different sellers and it still shows the PSRAM error.

The web server doesn't show up but only says Startup Failure: Insufficient PSRAM for app

**Comment by guece1** [comment]
I have this problem with my esp32s3 and OV5640

Compilation error: 'esp_spiram_get_size' was not declared in this scope

the problem is on Arduino core for the ESP32 3.0.0-rc1 and 3.0.0-alpha3
on 2.0.15 and 2.0.14 i ca compile but my cam module wont startup
Startup Failure: Camera init error 0xffffffff on CAMERA_MODEL_ESP32S3_EYE_FREENOVE
