### ISSUE TITLE
Slow FTP Upload Speed on ESP32S3 with ESP32-CAM_MJPEG2SD

### ISSUE THREAD

**Issue by Hossein-snb** [s60sc/ESP32-CAM_MJPEG2SD#364]
I am using the ESP32S3 development board to read files from the SD card and send them to the FTP server, but the speed is terribly slow. It takes about 10 minutes to upload a 10MB file.

Is there any way to get better speed?

Thank you for your help.

**Comment by s60sc** [comment]
The speed is dependent on the quality of your WiFi connection.
