### ISSUE TITLE
Planned recording time

### ISSUE THREAD

**Issue by Jeg777** [s60sc/ESP32-CAM_MJPEG2SD#368]
Hi, your app is great and the efforts you put in it are much appriciated including replying to every issue!
I would like to offer a feature to schedule the recording time from the GUI so it will enable to select days and hours in the week which it will record and in the rest it will go to sleep(based on the local time it gets from the internet). is it possible?

also, in one of your comments you said that in order to have it constantly recording the PIR should be enabled in the settings but which pin should be used in order for it to recorod as long as the device is on?

again, many thanks for your support!

**Comment by s60sc** [comment]
Thanks
Scheduling is possible but too much work for a specialist feature
PIR - choose a [free pin](https://github.com/s60sc/ESP32-CAM_MJPEG2SD#:~:text=Note%20that%20there%20are%20not%20enough%20free%20pins%20on%20the%20ESP32%20camera%20module%20to%20allow%20all%20external%20sensors%20to%20be%20used.%20Pins%20that%20can%20be%20used%20(with%20some%20limitations)%20are%3A%203%2C%204%2C%2012%2C%2013%2C%2033.) and assign it under web page `Edit Config / Peripherals`
