### ISSUE TITLE
Software reset due to exception/panic

### ISSUE THREAD

**Issue by Sanket2005** [s60sc/ESP32-CAM_MJPEG2SD#369]
i am facing the Software reset due to exception/panic  .. how to solve this error ??

20:02:00.287 -> 
20:02:00.287 -> 
20:02:00.287 -> [00:00:22.468 logSetup] =============== ESP-CAM_MJPEG 9.6 ===============
20:02:00.287 -> [00:00:22.478 printResetReason] Software reset due to exception/panic
20:02:00.287 -> [00:00:22.479 printWakeupReason] Wakeup by reset
20:02:00.363 -> [00:00:22.558 infoSD] SD card type SDHC, Size: 14.8GB
20:02:00.666 -> [00:00:22.558 listFolder] Sketch size 1.5MB
20:02:00.666 -> [00:00:22.857 listFolder] File: /data/configs.txt, size: 5540 bytes
20:02:00.666 -> [00:00:22.858 listFolder] SD_MMC: 18.9MB used
20:02:00.666 -> [00:00:22.858 loadConfig] Load config
20:02:00.935 -> [00:00:23.097 updateAppStatus] Enabling motion detection
20:02:00.935 -> [00:00:23.108 setup] PSRAM size: 8.0MB
20:02:01.166 -> [00:00:23.318 prepCam] Camera init OK for model OV2640 on board CAMERA_MODEL_AI_THINKER
20:02:01.398 -> [00:00:23.587 setWifiSTA] Wifi Station IP from DHCP
20:02:01.445 -> ....[00:00:25.580 onWiFiEvent] WiFi Station connection to supaspeed, using hostname: ESP-CAM_MJPEG_F4F70167B4FC
20:02:03.396 -> [00:00:25.591 onWiFiEvent] Wifi Station IP, use 'http://192.168.29.197' to connect
20:02:03.482 -> [00:00:25.634 onWiFiEvent] Wifi AP stopped: ESP-CAM_MJPEG_F4F70167B4FC
20:02:03.482 -> [00:00:25.635 onWiFiEvent] Wifi AP SSID: ESP-CAM_MJPEG_F4F70167B4FC started, use 'http://192.168.4.1' to connect

this is the error log

**Comment by s60sc** [comment]
Connect to serial monitor to catch stack trace then decode it
