### ISSUE TITLE
My ssid have spaces between letters

### ISSUE THREAD

**Issue by dipayandas2002** [s60sc/ESP32-CAM_MJPEG2SD#373]
My ssid has spaces between letters , but when I'm giving that input to the webpage at 198.164.4.1 it's showing me errors.

Like the spaces r not being taken care of.

What to do ?

**Comment by s60sc** [comment]
in `appGlobals.h` set `ALLOW_SPACES `to true

**Comment by dipayandas2002** [comment]
thanks
