### ISSUE TITLE
Frame rate change do not apply

### ISSUE THREAD

**Issue by nliaudat** [s60sc/ESP32-CAM_MJPEG2SD#38]
The frame rate change is not applied cause hardcoded in mjpeg2sd.cpp frameData[] 

`extern const frameStruct frameData[] = {
  {"96X96", 96, 96, 30, 1, 1}, 
  {"QQVGA", 160, 120, 30, 1, 1},
  {"QCIF", 176, 144, 30, 1, 1}, 
  {"HQVGA", 240, 176, 30, 2, 1}, 
  {"240X240", 240, 240, 30, 2, 1}, 
  {"QVGA", 320, 240, 30, 2, 1}, 
  {"CIF", 400, 296, 30, 2, 1},  
  {"HVGA", 480, 320, 30, 2, 1}, 
  {"VGA", 640, 480, 20, 3, 1}, 
  {"SVGA", 800, 600, 20, 3, 1}, 
  {"XGA", 1024, 768, 5, 3, 1},   
  {"HD", 1280, 720, 5, 3, 1}, 
  {"SXGA", 1280, 1024, 5, 3, 1}, 
  {"UXGA", 1600, 1200, 5, 3, 1}  
};`

As example, it's not possible to set HQVGA with 10 fps. 
Regards

**Comment by s60sc** [comment]
These are default values
