### ISSUE TITLE
how to add a buzzer in the circuit and make it enable on sensing the motion 

### ISSUE THREAD

**Issue by Sanket2005** [s60sc/ESP32-CAM_MJPEG2SD#384]
I want to add a buzzer to the connection so that it must start ringing when detected a motion and must stop after a while. So where should i connect it in the circuit and how can i make it work ?? and also thanks for the project code it is working perfectly

**Comment by s60sc** [comment]
As a starting point, in `mjpeg2sd.cpp` added `buzzerSound() `called from `processFrame()`

**Comment by Sanket2005** [comment]
but which pin should i connect the buzzer to and which location in the circuit
