### ISSUE TITLE
How to change the text that the telegram sends along with the image 

### ISSUE THREAD

**Issue by Sanket2005** [s60sc/ESP32-CAM_MJPEG2SD#388]
I have already used your program to sed telegram message. i want to send the text ""intruder detected "" how can i send that text that text ????

**Comment by DJprasenjit** [comment]
Send telegram is not working for me. Even I have 8MB PSram and 1.4MB Free PSRam memory. While starts the camera its shows error communicate telegram server. Using 9.6 version

**Comment by Sanket2005** [comment]
it does sometimes restart youe esp it will connect automatically again
