### ISSUE TITLE
[FEATURE REQUEST] ESPWebDav Support

### ISSUE THREAD

**Issue by rjsachse** [s60sc/ESP32-CAM_MJPEG2SD#389]
any thought of adding [EspWebDav](https://github.com/ardyesp/ESPWebDAV) to be able to access the filesystem over network, like a network drive

**Comment by s60sc** [comment]
I'll take a look

**Comment by rjsachse** [comment]
I'm currently using it with another project for my cnc machine and thought it would be good ideas for this project to be able to see the files in Windows Explorer

**Comment by s60sc** [comment]
in v9.7
