### ISSUE TITLE
[ERROR] Insufficient PSRAM for app 

### ISSUE THREAD

**Issue by soyabeannnn** [s60sc/ESP32-CAM_MJPEG2SD#392]
How should I fix this error

08:22:36.782 -> [00:00:05.570 ERROR @ ESP32-CAM_MJPEG2SD.ino:34] Startup Failure: Insufficient PSRAM for app

**Comment by s60sc** [comment]
dont buy fake boards

**Comment by jaochoo** [comment]
If you use platform.io try this board configuration

[env:ESP32]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
lib_deps =
  esp32-camera

**Comment by tanushsahoo** [comment]
Exact same issue here and I use arduino IDE for programming the board with the board selected as ai thinker esp32 -cam. If someone can help me out it would be greatly appreciated

**Comment by s60sc** [comment]
dont use fake boards with only 2M psram
