### ISSUE TITLE
[ISSUE] Programming in VSCode with PlatformIO

### ISSUE THREAD

**Issue by MATE3942** [s60sc/ESP32-CAM_MJPEG2SD#399]
I'm trying to program the ESP32 using ProgramIO. Although everything seems to work fine, the board isn´t able to recognize the SD card, so when I go to the station IP, it only shows "Startup Failure: Check SD card inserted". Does it have anything to do with me not using the Arduino IDE?

**Comment by rjsachse** [comment]
What board are you trying to flash? Not a issue with playformio as I use that with my custom board.

**Comment by rjsachse** [comment]
Ok you might have to define the pins "SD_MMC_CMD 15, SD_MMC_CLK 14, SD_MMC_DATA 2 in platformio. Either in the platformio.ini or in appGlobals.h around line 133. Or use arduino. Sorry haven't tried Ai Thinker Cam in platformio

**Comment by rjsachse** [comment]
Have you tried in arduino?

**Comment by rjsachse** [comment]
Is the card formatted right?

**Comment by rjsachse** [comment]
Do you have the data folder on the sd card. What is in the logs. Does it say "card mount failed"

**Comment by rjsachse** [comment]
Sorry I am stumped on this. I will have a look when I get off work. Have you tried another sd card by any chance

**Comment by rjsachse** [comment]
Maybe try a fresh install of mjpeg2sd and don't change nothing in the files  and select board and partition and flash.

**Comment by rjsachse** [comment]
So the SDMMC_TEST under arduino examples works with no issues

**Comment by rjsachse** [comment]
This issue might be hardware. Alot of cheap clones out there. Might not have pull ups on the lines. The other projects that works are they using sdmmc or spi for sd

**Comment by rjsachse** [comment]
Seems OK. Beside not able to delete file. The sd card seems small 384mb should not matter. Have you tried a different card

**Comment by rjsachse** [comment]
Sorry my mistake.

**Comment by s60sc** [comment]
I can only suggest that the pinout of the board you are using does not match the configured board.

**Comment by s60sc** [comment]
try downloading a fresh copy of the app in case you have corrupted it

**Comment by s60sc** [comment]
No, the problem is specific to your environment, not the app

**Comment by rjsachse** [comment]
Have you changed any settings before uploading? Do you have the right board selected? Do you have the right partition selected? Have you tried latest version 9.7a? Format card to FAT32. Try erasing flash before upload.

I can upload the project straight to a new espcam not changing any settings and just select right board, partition.

Hope you work it out

**Comment by lockiz** [comment]
@mateoavalose Hi, did you figure out the problem?

**Comment by mateoavalose** [comment]
> [@mateoavalose](https://github.com/mateoavalose) Hi, did you figure out the problem?

No, I gave up
