### ISSUE TITLE
Sketch exceeding program storage space

### ISSUE THREAD

**Issue by hadiudoit11** [s60sc/ESP32-CAM_MJPEG2SD#402]
Using the ESP32CAM (with ftdi).
Here's how I set up the appGlobals.h  _(everything is false)_

#define INCLUDE_FTP_HFS false
#define INCLUDE_SMTP false   
#define INCLUDE_MQTT false    
#define INCLUDE_TGRAM false  
#define INCLUDE_CERTS false   
#define INCLUDE_TELEM false   
#define INCLUDE_MIC false 
#define INCLUDE_UART false   

#define INCLUDE_TINYML false  
#define INCLUDE_DS18B20 false 

Getting this error:

Sketch uses 1413293 bytes (107%) of program storage space. Maximum is 1310720 bytes.
Global variables use 89092 bytes (27%) of dynamic memory, leaving 238588 bytes for local variables. Maximum is 327680 bytes.

**Comment by s60sc** [comment]
Compile with  Minimum spiffs scheme
