### ISSUE TITLE
[ISSUE] Subtitles don't work in windows media player

### ISSUE THREAD

**Issue by rjsachse** [s60sc/ESP32-CAM_MJPEG2SD#403]
Hi, I kept getting a error message when playing a video in windows media player, that it can't read the subtitle file from telemetry.

looking into this the format needs to be
> hours:minutes:seconds,milliseconds
>  00:00:00,000 --> 00:00:01,000

 not 
>  hours:minutes:seconds
> 00:00:00 --> 00:00:01

I manually changed a srt file with ,000 milliseconds and it worked.

**Comment by s60sc** [comment]
uploaded fix

**Comment by rjsachse** [comment]
Thank you, glad it was a easy fix
