### ISSUE TITLE
[Feature Request] Arduino OTA

### ISSUE THREAD

**Issue by rjsachse** [s60sc/ESP32-CAM_MJPEG2SD#406]
Just to make programming the board a bit easier would be good if it has ArduinoOTA as well so can flash wireless from arduino. Don't know if better to use libary or try to implement  natively, seems like it looks for a port 3232 and mdns broadcast.

**Comment by s60sc** [comment]
Use arduino to export compiled binary then app OTA tab to upload bin file

**Comment by rjsachse** [comment]
Yer that's the way currently, just wondering if could add ArduinoOTA too so don't need export then go to app the ota page and upload binary.

Would be easier to just flash from arduino no other steps involved. Just makes prototyping easier and faster.
