### ISSUE TITLE
data\MJPEG2SD.htm ... Trojan:Script/Wacatac.H!ml ?

### ISSUE THREAD

**Issue by TinkerType** [s60sc/ESP32-CAM_MJPEG2SD#408]
After getting the repository on a Windows 10 machine, MS Defender warned that the file in folder
`data\MJPEG2SD.htm`
is Trojan:Script/Wacatac.H!ml. 

Is s60sc or anybody else aware of this issue? Is this an issue or a false positive? I have not had the time to go through the code myself but would appreciate your feedback. Thanks very much.

**Comment by TinkerType** [comment]
![ms_defender_alert](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/166581556/3cf26cd8-a9a3-4873-b9f6-02149316eaa7)

**Comment by s60sc** [comment]
False positive from latest defender update

**Comment by TinkerType** [comment]
Thanks!

**Comment by s60sc** [comment]
now fixed by microsoft
