### ISSUE TITLE
[bug] Camera init error 0xffffffff with esp32s3 and OV5640

### ISSUE THREAD

**Issue by guece1** [s60sc/ESP32-CAM_MJPEG2SD#411]
I have this problem with my esp32s3 and OV5640 

my esp32s3 is this https://github.com/Freenove/Freenove_ESP32_S3_WROOM_Board

Compilation error: 'esp_spiram_get_size' was not declared in this scope

this problem exist on Arduino core for the ESP32 by Espressif Systems 3.0.0-rc1 and 3.0.0-alpha3

on 2.0.15 and 2.0.14 i can compile but my cam module wont startup
Startup Failure: Camera init error 0xffffffff on CAMERA_MODEL_ESP32S3_EYE_FREENOVE

my configs 
Board = ESP32S3 Dev Module
flash size 8mb
8m with spiffs
opi Psram
(no problem with OV2640 on Arduino core for the ESP32 by Espressif Systems 2.0.15)

**Comment by s60sc** [comment]
Bug awaiting fix due to combination of S3 and OV5460 trying to allocate too much PSRAM

In the interim, in `appGlobals.h,` change:
`#define FB_BUFFERS 12 // 1 being processed, rest being filled`
to:
`#define FB_BUFFERS 6 // 1 being processed, rest being filled`

**Comment by guece1** [comment]
appreciate for your time and help.  now everything works

**Comment by s60sc** [comment]
should be fixed in v9.7.1
