### ISSUE TITLE
[Bug] Default IP address not shown in log for ESP32 Wrover Dev Board

### ISSUE THREAD

**Issue by soyabeannnn** [s60sc/ESP32-CAM_MJPEG2SD#417]
Error:

22:42:36.187 -> [00:00:00.456 logSetup] =============== ESP-CAM_MJPEG 9.7 ===============
22:42:36.187 -> [00:00:00.466 logSetup] Compiled with arduino-esp32 v2.0.15
22:42:36.187 -> [00:00:00.466 printResetReason] Power on reset
22:42:36.187 -> [00:00:00.477 printWakeupReason] Wakeup by reset

It only shows up to the message above 

I am using a ESP32 Wrover Dev Board, with a MicroSD card adapter while its connected to the ftdi, all connections are correct however it doesn't show the IP address for the web server when reset button is pressed. There was no errors upon compiling the code.

**Comment by s60sc** [comment]
the bug is your serial connection
