### ISSUE TITLE
re: CAMERA_MODEL_NEW_ESPS3_RE1_0 SD_MMC pins

### ISSUE THREAD

**Issue by OldYin** [s60sc/ESP32-CAM_MJPEG2SD#418]
I know you intended to get these right but a minor typo makes them wrong. I know that anybody who actually owns one of these boards, won't be confused... for long but I figured you would like to correct this.

In camera_pins.h
You have:

//Define SD Pins
#define SD_MMC_CLK 42
#define SD_MMC_CMD 39
#define SD_MMC_D0 4

Correct pins are:

//Define SD Pins
#define SD_MMC_CLK 42
#define SD_MMC_CMD 39
#define SD_MMC_D0 41

Regards,
Alex

**Comment by s60sc** [comment]
Thanks. I dont have this board myself so see if @rjsachse will confirm as they provided the update

**Comment by rjsachse** [comment]
Good morning, I don't have that board either. I just copied the pins from appGlobals.h and pasted in camera_pins.h I noticed the board got added in march in version 9.62. Surprisingly you are the first to noticed. Easy fix.

**Comment by rjsachse** [comment]
Pull Request done

**Comment by OldYin** [comment]
If I may refer you to issue #379 in which mamazad7 posted full pin details (with diagrams) for this board. Hope that helps. 
Also I DO have this board :)

regards,
Alex

**Comment by rjsachse** [comment]
Been fixed just waiting on @s60sc to accept pull request, it was a typo in version 9.62.

**Comment by OldYin** [comment]
No worries; thanks :)
