### ISSUE TITLE
Telegram message notification

### ISSUE THREAD

**Issue by ldijkman** [s60sc/ESP32-CAM_MJPEG2SD#427]
Telegram message notification

would it not be nice to have a link to the sttream in the telegram message?

not so nice wide angle night vision cam

![Screenshot from 2024-05-05 13-42-35](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/45427770/f6bd7888-32d3-40fc-8713-dcbd1778b73d)

**Comment by s60sc** [comment]
I dont think the telegram bot api supports streaming, its message based.

**Comment by ldijkman** [comment]
i was think more like a doorbell cam
if input is high or low send telegram message
with a handy stream link that will open in browser 
a message like next

doorbell  
see http://localip/stream  http://externalip/stream

**Comment by s60sc** [comment]
not sure what value is, you could bookmark url
