### ISSUE TITLE
AP SSID name

### ISSUE THREAD

**Issue by lygiabao3824** [s60sc/ESP32-CAM_MJPEG2SD#428]
Hi, I'm new to esp32cam. I want to ask how to change this AP's name
![Screenshot 2024-05-11 004453](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/129777973/84c10daf-c17e-46a0-b76e-0a048a20ff67)

**Comment by s60sc** [comment]
on web page Edit Config / Wifi / AP SSID name
