### ISSUE TITLE
PSRAM issue

### ISSUE THREAD

**Issue by Abasithdev** [s60sc/ESP32-CAM_MJPEG2SD#438]
Hi guys, do you about this? how to solve?
`00:35:05.141 -> [00:00:03.631 WARN setup] Startup Failure: Need PSRAM to be enabled `

**Comment by MahmoudBachebouch** [comment]
I have the same issue

**Comment by walera3103** [comment]
The same issue

**Comment by walera3103** [comment]
[00:00:00.213 setWifiSTA] Wifi Station IP from DHCP
.....[00:00:02.633 onWiFiEvent] WiFi Station disconnected
.....[00:00:05.041 onWiFiEvent] WiFi Station disconnected
[00:00:05.220 WARN startWifi] SSID POCO_X5_Pro_5G not available, use AP 
[00:00:05.220 ERROR @ utils.cpp:66] mDNS host:  Failed 
[00:00:08.009 startPing] Started ping monitoring - On
[00:00:08.011 startWebServer] Starting web server on port: 80
[00:00:08.012 ERROR @ ESP32-CAM_MJPEG2SD.ino:182] Startup Failure: Need PSRAM to be enabled 
[00:00:13.010 resetWatchDog] WatchDog started using task: ping
E (46278) ping_sock: send error=0
E (76278) ping_sock: send error=0

**Comment by Abasithdev** [comment]
I found a configuration here if you use arduino IDE
![image](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/28683194/4aa8e7d7-a85e-4089-b455-0865573361fb)

But after running the compile and upload. the serial show 
`12:59:56.783 -> [00:00:04.279 WARN setup] Startup Failure: Insufficient PSRAM for app `

**Comment by Abasithdev** [comment]
But the developer said this is can expected because of board specs. 
https://github.com/s60sc/ESP32-CAM_MJPEG2SD?tab=readme-ov-file#esp32-cam_mjpeg2sd

but is any chance to fix it? @s60sc

**Comment by Abasithdev** [comment]
after search the log location. I found this
![image](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/28683194/512cf1b2-c74b-4aea-9ffd-6bfd35f16a56)

I think need adjust PSRAM size with flash size and partition type. for example my board size is 2MB, so I need to choose the config like this
![image](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/28683194/121e586f-3abe-4188-891b-08baea977233)

I don't know it is works or not. still in upload progress

**Comment by s60sc** [comment]
app too complex for 2MB psram, min 4MB required

**Comment by walera3103** [comment]
> I found a configuration here if you use arduino IDE ![image](https://private-user-images.githubusercontent.com/28683194/333775802-4aa8e7d7-a85e-4089-b455-0865573361fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDg1MzYsIm5iZiI6MTcxNjY0ODIzNiwicGF0aCI6Ii8yODY4MzE5NC8zMzM3NzU4MDItNGFhOGU3ZDctYTg1ZS00MDg5LWI0NTUtMDg2NTU3MzM2MWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDE0NDM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYzI0Y2YxYTQ2ZjhhNWYyZjA4NTExMWU3MWM5OGMwNmRiMDhhNjRhOWI0MmYwN2M5YTJmNTdkZjA5Yjc3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VriHQWBPkjmk7fmdV6Z0dEFaUdwN-8iJnH6iUW7WAvA)
> 
> But after running the compile and upload. the serial show `12:59:56.783 -> [00:00:04.279 WARN setup] Startup Failure: Insufficient PSRAM for app `

this helped me, thank you

**Comment by MahmoudBachebouch** [comment]
No solution ??

**Comment by Abasithdev** [comment]
> No solution ??

It depends on your board it is support or not

**Comment by Abasithdev** [comment]
maybe I can close this issue, thanks all, thanks @s60sc
