### ISSUE TITLE
is it possible to delete a complete directory file, e.g. a day, from the SD Card

### ISSUE THREAD

**Issue by burkadius** [s60sc/ESP32-CAM_MJPEG2SD#44]
This is not an error message, just a question: If you want to delete a complete directory (e.g. a day) from the SD card, this does not work. You first have to delete the contents of the directory file by file and then you can delete the entire directory.
This is of course very complicated. Is there another solution? Format the SD card, for example?
Many greetings
Burkhard

**Comment by s60sc** [comment]
Found that this is due to a change in esp32-arduino v2.0.0 which I'll address in the coming days

**Comment by burkadius** [comment]
Hi, Yes it works perfect
Thans 
Burkhard
