### ISSUE TITLE
[FEATURE UPDATE - TESTING] External heartbeat

### ISSUE THREAD

**Issue by alojzjakob** [s60sc/ESP32-CAM_MJPEG2SD#446]
This was a productive weekend :D

I invite everyone interested to test external heartbeat feature by using www.espsee.com.
It is a website built with wordpress and a custom plugin i just created which:
- handles heartbeat payloads
- **automatically adds your cameras if you used token provided under your espsee user account**
- displays all your cameras with up to date (dynamic) IP addresses
- shows camera active/incative status based on last heartbeat receive time

After a successful test i plan to opensource the plugin and we can also make epseee.com a default value in the camera settings screen

P.S. I wanted to make all cameras open in iframe, but since the cameras are not working smoothly with https enabled (ESP32-CAM from aliexpress at least), I cant load http into iframe on https website :( But still, this is nice to have to provide all your camera links in one place.
I plan to add grouping in the future so you can organize your cameras :)

@s60sc am I allowed to use this repository link as a reference in the how to guide that will sit on this website?

![Screenshot_%Y%M%D_%H%m%S-12](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/17972823/0438b49a-20eb-4a0f-8ecc-d4352eabb8af)

![Screenshot_%Y%M%D_%H%m%S-14](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/17972823/8a30116f-b7dc-4609-8e1b-781308f69e4e)

**Comment by s60sc** [comment]
Youre welcome to add a reference. 
You should add a privacy policy.

**Comment by alojzjakob** [comment]
Added EspSee as a hinted setting in external heartbeat feature's option.
Added explanation to the main readme.

Also added initial privacy policy: https://www.espsee.com/privacy-and-terms/, if you have any suggestions, please tell me :)
Added: https://www.espsee.com/about/

**Comment by alojzjakob** [comment]
@s60sc as promised: https://github.com/alojzjakob/EspSee

cheers!

**Comment by s60sc** [comment]
added link to readme
