### ISSUE TITLE
URL for a still-image?

### ISSUE THREAD

**Issue by vermoi63** [s60sc/ESP32-CAM_MJPEG2SD#449]
Dear developer, this is really great, great work, Tks for sharing this!!

Is there a way to have a URL that is capturing only a still-image in an external browser?
(background: want to put it in Home Assistant as a generic camera, or grap it with a "wget" request...)
I found the one for streaming, but not the one for still images without using the internal WEB Menu.

Kind regards!

**Comment by s60sc** [comment]
Thanks

```
// Direct access URLs for NVR:
// - Video streaming: app_ip/sustain?video=1 
// - Audio streaming: app_ip/sustain?audio=1
// - Subtitle streaming: app_ip/sustain?srt=1
// - Stills: app_ip/control?still=1
```

**Comment by vermoi63** [comment]
Tks, really really great....the still one simply not listed in documentation....just integrated in Home Assistant for 10 sec stills in the picture-glance and works great in parallel to the native firmware function!!!!

**Comment by vermoi63** [comment]
Many Thanks for the hint to the still-image URL!
