### ISSUE TITLE
Close time-laps file when turning time-laps switch off

### ISSUE THREAD

**Issue by vermoi63** [s60sc/ESP32-CAM_MJPEG2SD#450]
in 9.7.3 timelaps need to finalize one circle to get stored in the folder for the day......
In very long time laps cycles it could be helpfull that not waiting to the end of the circle and simply turning off (break) the time laps recording with storing the file so far as captured.....

Kind regards!

**Comment by s60sc** [comment]
Use shorter duration, so several files per day

**Comment by vermoi63** [comment]
Yes, I did already shorten the period, and link the time laps files in an external app!
Great Thanks!

**Comment by vermoi63** [comment]
Done
