### ISSUE TITLE
HTTPS file sending example

### ISSUE THREAD

**Issue by bjesuslopezg** [s60sc/ESP32-CAM_MJPEG2SD#455]
Hello, I've been using this app for a while to record videos using an ESP32S3 MCU, video recording works fine, however I have this particular requirement in which I need to send the recorded videos to an HTTPS server. It is of my understanding that this app supports HTTPS video sending but it seems to lack some examples on how to achieve it.

I located the file ftp.cpp, and I've already changed the mode from FTP to HFS using the web interface

![web_interface](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/63483248/57b18e1d-bcc8-4469-b1ce-d3c42ce0dbe8)

However, I'm still really clueless on how to connect to the server and send the files. I believe it has something to do with these macros on the ftp.cpp file

![image](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/63483248/e8e45ae9-483c-42aa-a2bf-0780b3d1701f)

**Comment by s60sc** [comment]
Fill in the FS details on the web page and press File Upload button. The HTTPS server needs to process the http post message sent.

**Comment by GerardoPrototype** [comment]
> Fill in the FS details on the web page and press File Upload button. The HTTPS server needs to process the http post message sent.

Hello, before asking, I wanted to congratulate you on the enormous work you contribute, thank you very much.

I had the same question about whether it is possible to send HTTP POST requests without having to specify the certificate. I created a server with an endpoint that receives a file through form-data, and the file is called "video."

I wanted to ask where exactly you have to specify the file name and where to put the URL.
Apologies if this part is not entirely clear to me.

<img width="725" alt="Captura de pantalla 2024-07-03 a la(s) 11 23 38 a m" src="https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/133162777/043a1c8a-f6af-49e4-97c3-35e98c3bb99c">

**Comment by s60sc** [comment]
Thanks
The url is built automatically from the info entered on the web page and the file or folder name selected from the drop down list. You need to provide certs for the esp in the certificates.cpp file to use https. The https server public cert is optional if youre not worried about server spoofing.
