### ISSUE TITLE
64GB SD Card Near Capacity After Software Installation

### ISSUE THREAD

**Issue by khcruz642** [s60sc/ESP32-CAM_MJPEG2SD#457]
Hi!

I recently flashed the software for my ESP32-CAM onto a 64GB SD card, and now it's almost at full capacity. The card is filled with files that have random characters and cannot be deleted. Additionally, there seems to be an issue where the videos saved by the ESP32-CAM are not actually being stored on the SD card.

Has anyone encountered this problem before? Any suggestions on how to fix this?

I've attached images for reference.

Image 1:
Capacity
![image](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/153230038/fca02bc8-c2a5-4894-8670-8248d1cdc8aa)

Image 2:
Contents
![image](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/assets/153230038/e631adfb-8cd1-4885-91ad-6e22c4a238be)

**Comment by s60sc** [comment]
app only tested on up to 32gb
