### ISSUE TITLE
[Bug] AP active and accessible without password after disabled "Allow simultaneous AP"

### ISSUE THREAD

**Issue by guece1** [s60sc/ESP32-CAM_MJPEG2SD#460]
Installed v9.9.1 - connected to my ssid - disabled "Allow simultaneous AP" - assigned fixed ip - even changed AP SSID name and AP Password
But the standart AP ESP-CAM_MJPEG_********* is all the time active and accessible without password
this is a serious security issue 

compiled with arduino core v3.0.3

update 
a litte workaround
after defining Authentication settings  - the AP change the name and is secured with pass but it is broadcasting all the time

**Comment by s60sc** [comment]
return of rogue AP - fix uploaded

**Comment by guece1** [comment]
fix working

thank you
