### ISSUE TITLE
Guru Meditation Error: Core 1 panic'ed (StoreProhibited). Expection was unhandled

### ISSUE THREAD

**Issue by EP-man** [s60sc/ESP32-CAM_MJPEG2SD#461]
I've been using this app for my eps32-cam for a while to record videos and it has been great, but recently i got this error when using some features from app (like starting a capture)

![Screenshot 2024-07-22 131025](https://github.com/user-attachments/assets/d763a498-7535-4ba1-adeb-48b26d84f35b)

I have no idea why this happened to me. but i'm suspicious about the last app i had flashed to the esp32-cam (it was esp32_nat_router).
I would be happy if my problem be solved sooner, i really need it for home security.

**Comment by s60sc** [comment]
Do a clean instal of the latest version
