### ISSUE TITLE
server issue

### ISSUE THREAD

**Issue by Atharvamaj** [s60sc/ESP32-CAM_MJPEG2SD#466]
![image](https://github.com/user-attachments/assets/48e7f500-6091-49e2-ae92-9cc1c383ee00)
this is what i get what can i do i even flashed a blank sketch and I used the actual name rather then esp32 dev module

**Comment by rjsachse** [comment]
not a issue look through other issue to find your problem. did you read the readme

**Comment by Atharvamaj** [comment]
yes
