### ISSUE TITLE
DFRobot Firebeetle ESP32S3 Support

### ISSUE THREAD

**Issue by maximagination1** [s60sc/ESP32-CAM_MJPEG2SD#467]
Hi there,

On another topic, does your code support the Firebeetle 2 Board (ESP32-S3-U) from DFRobot? https://www.dfrobot.com/product-2677.html

I assume it is compatible, as I can see its previous version (ESP32S3) with pins listed in camera_pin.h. Please let me know if the **-U** version of this ESP32S3 board is compatible.

Also, could I connect an SPI micro SD card module to the board to save recorded files?

Thanks.

Max

**Comment by s60sc** [comment]
The app will support any board with ov2640/5640  cam provided the pin def exists in camera_pins.h, so check that the new board has the same pinout, if not another def needs to be added.

Only a sdmmc module is supported for SD. Spi for SD is slow anyway.

**Comment by s60sc** [comment]
any 3 pins should work, assign to:
SD_MMC_CLK 
SD_MMC_CMD
SD_MMC_D0
