### ISSUE TITLE
CAMERA_MODEL_ESP32S3_EYE_FREENOVE In camera_pins.h But Not Elsewhere

### ISSUE THREAD

**Issue by mrmonteith** [s60sc/ESP32-CAM_MJPEG2SD#469]
This might be a cleanup issue.  But found out that CAMERA_MODEL_ESP32S3_EYE_FREENOVE is in the camera_pins.h, but not in the appGlobals.h

**Comment by rjsachse** [comment]
either CAMERA_MODEL_ESP32S3_EYE or CAMERA_MODEL_FREENOVE_ESP32S3_CAM will select CAMERA_MODEL_ESP32S3_EYE_FREENOVE this is not a issue

**Comment by mrmonteith** [comment]
But, if it's in there shouldn't it be i the appGlobals.h?  Is there a need for CAMERA_MODEL_ESP32S3_EYE_FREENOVE to be in there?

**Comment by rjsachse** [comment]
There is 2 boards under CAMERA_MODEL_ESP32S3_EYE_FREENOVE that is a just a define for log. It is ment to be like.
