### ISSUE TITLE
Startup Failure: Crash loop detected

### ISSUE THREAD

**Issue by dodomart1234** [s60sc/ESP32-CAM_MJPEG2SD#476]
i was seeing this error "Startup Failure: Crash loop detected" and i see some videos comments they are also facing this problem please help i have a esp32S cam and i selected ai thinker model. this error is printed on serial monitor and web server both

**Comment by s60sc** [comment]
[#468](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/issues/468)

**Comment by dodomart1234** [comment]
thanks a lot i get it now
