### ISSUE TITLE
Change wifi function

### ISSUE THREAD

**Issue by DjF0589** [s60sc/ESP32-CAM_MJPEG2SD#477]
Can you help me on how to change the wifi function so as to make the esp32 a wifi soft access point instead of having to connect it to a router? What lines should i change and how?

**Comment by s60sc** [comment]
AP already there as per readme:
`On first installation, the application will start in wifi AP mode - connect to SSID: ESP-CAM_MJPEG_..., to allow router and password details to be entered via the web page on 192.168.4.1.`
