### ISSUE TITLE
Can't download a video file, suddently, crashes at 75% 

### ISSUE THREAD

**Issue by davemaster** [s60sc/ESP32-CAM_MJPEG2SD#479]
Greetings,

I'm using this camera server, and the power problems aside, it's impossible to download a file from the SD, the download never get the 100%.

![imagen](https://github.com/user-attachments/assets/a7f37807-12bb-40c9-a11c-5586028f8ec4)

Thanks in advance

PD. I'm using the Firefox Browser

**Comment by s60sc** [comment]
what does log show
