### ISSUE TITLE
Will not compile

### ISSUE THREAD

**Issue by PRMackwood** [s60sc/ESP32-CAM_MJPEG2SD#48]
Hi
I came to this repository by way of the instructable by Max Imagination.
[https://www.instructables.com/How-to-Make-a-WiFi-Security-Camera-ESP32-CAM-DIY-R/](url)
The instructable was written December 28 last year and it seems you have changed a lot of the code since then, and I cannot get the code to compile using the Arduino IDE nor using VSCode with PlatformIO.

I am sure there will be other people who struggle which is a shame as the code appears to be well written and comprehensive.

I have attached the Arduino compiler output - any assistance would be appreciated

Regards,
Paul

[compiler output.txt](https://github.com/s60sc/ESP32-CAM_MJPEG2SD/files/7881426/compiler.output.txt)

**Comment by s60sc** [comment]
Thanks
You are using arduino-esp32 v1.0.6 which is out of date
Try upgrading to arduino-esp32 v2.0.2
