### ISSUE TITLE
WLAN hangs up too often whean video streaming with fast changes in content

### ISSUE THREAD

**Issue by vermoi63** [s60sc/ESP32-CAM_MJPEG2SD#483]
WLAN hangs up (only ping watchdog) in video streaming always when lots of changes in image occur.
-code V 9.9.4
-arduino board manager for espressif 3.0.4
-board esp32cam AI thinker

Any idea to get this stable?
(also occurs in CIF resolution with only 1 fps)

to be added:
happens only when motion detect is ON AND streaming is ON
(same without streaming and only recording to SD works fine)

**Comment by vermoi63** [comment]
to be added: happnes only when motion detect is ON AND doing streaming
(same without streaming and only recording to SD works fine)

**Comment by s60sc** [comment]
streaming bandwidth entirely dependent on wifi signal quality

**Comment by vermoi63** [comment]
Thank you for the response,
I found out that turning motion-detection OFF while downloading or streaming works well (no WLAN restart occurs);
so I assume simply the processor is not fast enough - at least this is a workaround for week CPU' (esp32)
Just ordered a S3 to see if it manages motion-detection AND download or streaming better

Thanks again for all the engineering you provide!

**Comment by vermoi63** [comment]
ddd
