### ISSUE TITLE
(only) in night-mode pictures are corrupted

### ISSUE THREAD

**Issue by vermoi63** [s60sc/ESP32-CAM_MJPEG2SD#484]
in current version images sent by smtp are damaged when night mode is on
this can be tested by adjusting the night-level to night/day while having same light conditions
-strange- why the program-mode has an influence on this...

Thanks for the great work anyhow!!!

**Comment by s60sc** [comment]
bug to fix - emails shouldnt be sent in night mode

**Comment by s60sc** [comment]
fixed in 10.2.1
