### ISSUE TITLE
Remote mic is always Off

### ISSUE THREAD

**Issue by madiglechat** [s60sc/ESP32-CAM_MJPEG2SD#492]
Hello,

Very nice job, thanks for this program.

Unfortunatelly, I have a trouble with the microphone, I can't use it, it's always on OFF, even if I configure it on ON on the browser.
![image](https://github.com/user-attachments/assets/c7bd26ad-74f4-4c30-9026-a693af99e172)
I use a Xaio ESP32S3 card and I want to change the microphone pins number but it's the same problem, the pin WS stay always with the value 41 even if I change it to 42 like in the picture, same trouble with the SD pin.

Thanks for your help.

**Comment by s60sc** [comment]
You cant change the esp mic pins they are fixed in the xaio hardware.
The esp mic is local, the remote mic is the browser which will only work if you have an amp/speaker on the esp

**Comment by madiglechat** [comment]
In the file camera_pins.h section xiao ESP32S3 the hardware is well defined:
![image](https://github.com/user-attachments/assets/d062e10f-8bd4-4b42-91c9-12c96c2d87e8)
But in the browser the I2S WS is 41 and the I2S SD is 42, if I change it, save the config, it always come back to the WS=41 and SD=42, and my records have no sound...
