### ISSUE TITLE
Unable to change config file

### ISSUE THREAD

**Issue by jantyka** [s60sc/ESP32-CAM_MJPEG2SD#502]
Hello, first time writing here. I already checked if i am the only one with that issue, maybe i am missing something.
FTP / HTTPS and Telegram credentials changed via WebUi are not being saved.

`[01:43:10.957 savePrefs] Saved preferences
[01:43:10.998 saveConfigVect] Config file saved` 

All videos are being saved just fine on the SD card, and the data folder with the configs.txt is also present, but the files seems to be untouched.

What i tried so far:

- Connected with AP and LAN to change settings
- Cleared cache
- Tried different browsers on different systems (Linux / Windows)
- Used incognito mode
- Reformatted the SD card
- Started over

Hardware ESP32S

Appreciate your help/assistance in advance

**Comment by s60sc** [comment]
as per readme
Optional features are not included by default. To include a feature, in appGlobals.h set relevant #define INCLUDE_* to true.
