### ISSUE TITLE
Error: disableRangeSlider is not defined

### ISSUE THREAD

**Issue by limengdu** [s60sc/ESP32-CAM_MJPEG2SD#503]
I used the latest version of the code with XIAO ESP32S3 Sense, esp-arduino version 3.0.5. compiling and uploading went very smoothly, no problems. But when I use Chrome, I encounter Error: disableRangeSlider is not defined when I open the web page. then I can't click on anything to get the screen.
![image](https://github.com/user-attachments/assets/17c09d63-eade-49b0-984d-c07b5e3d0db2)

**Comment by s60sc** [comment]
you may have an old common.js cached, otherwise ota latest

**Comment by limengdu** [comment]
Thanks for your help, I updated the data folder and the programme runs smoothly. But I can never get the sound of the recorded video on XIAO. I don't know where else I'm missing.
![uIpQHSHVs0](https://github.com/user-attachments/assets/17d888e0-86d8-44ff-bb56-904df584d021)
![x5fNVqPJtH](https://github.com/user-attachments/assets/fc10877b-a72c-440f-bb7d-79e44d69c62c)

**Comment by s60sc** [comment]
pins numbers transposed, a corrected version of audio.cpp uploaded
