### ISSUE TITLE
I2C library issue

### ISSUE THREAD

**Issue by rjsachse** [s60sc/ESP32-CAM_MJPEG2SD#508]
Firstly, excellent work once again. I apologize for only now getting around to testing the I2C components and encountering an issue with the inclusion of SSD1306Wire.h. It appears to be intended for Arduino rather than ESP32. Below is the error message.

```
c:\Users\rohan\OneDrive\Documents\libraries\SSD1306wire\src\SSD1306wire.cpp:1:10: fatal error: avr/pgmspace.h: No such file or directory
    1 | #include <avr/pgmspace.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1
```

What library are you using?

**Comment by s60sc** [comment]
https://github.com/ThingPulse/esp8266-oled-ssd1306
ill add a comment

**Comment by rjsachse** [comment]
Thanks found a few libraries with SSD1306wire.h
