### ISSUE TITLE
text section exceeds available space in board

### ISSUE THREAD

**Issue by herbbetz** [s60sc/ESP32-CAM_MJPEG2SD#516]
I try flashing the Freenove_ESP32_S3_WROOM_Board using Arduino IDE 2.3.3 . The Board Manager seems the current version (https://github.com/espressif/arduino-esp32, https://dl.espressif.com/dl/package_esp32_index.json). I emptied the board (python -m esptool --port COM3 erase_flash) and the 1 GB SDcard is inserted. Still I get this compilation error: 
       
        Sketch uses 1576309 bytes (120%) of program storage space. Maximum is 1310720 bytes.
        Sketch too big; Compilation error: text section exceeds available space in board

**Comment by s60sc** [comment]
See readme:

Select the ESP32 or ESP32S3 Dev Module board and compile with PSRAM enabled and the following Partition scheme:

ESP32 - Minimal SPIFFS (...)
ESP32S3 - 8M with spiffs (...) or 16MB(3MB APP...)
