### ISSUE TITLE
NOT ABLE TO PERFOM OTA UPDATE

### ISSUE THREAD

**Issue by MayoorTech** [s60sc/ESP32-CAM_MJPEG2SD#524]
first i must say you have done a wondaful work with this project, 

however being a new bee with esp am unable to do OTA updates, am currently running on v9.9.1 please what steps do i need to take and which particular files do i need to download to achieve OTA update to v9.9.4 
please how is it done..?

thanks for replying.

![Screenshot 2024-12-15 142724](https://github.com/user-attachments/assets/4eee436e-8536-49e1-9437-c270ba20ccf7)
![Screenshot 2024-12-15 144147](https://github.com/user-attachments/assets/c4fab5fb-e409-4e28-9e29-6ac621296316)

**Comment by s60sc** [comment]
In arduino generate a bin file for v9.9.4 using Sketch > Export compiled Binary
Then select bin file in ota web page
