### ISSUE TITLE
I FOUND SAME problem for arduino 2.0

### ISSUE THREAD

**Issue by MRHERT** [s60sc/ESP32-CAM_MJPEG2SD#56]
can i send you more pictures to show you the problem ?

**Comment by s60sc** [comment]
It has nothing to do with the app. Your  File library is out of date - I cant help with Arduino problems

**Comment by nnjim** [comment]
@MRHERT

As s60sc stated you need to update your ESP32 library to 2.0.2. He is not refering to the Arduino IDE version. You need to go into board manager in the IDE and check the ESP32 version.
