### ISSUE TITLE
HTML fails to load

### ISSUE THREAD

**Issue by pgodd** [s60sc/ESP32-CAM_MJPEG2SD#63]
Using today's build (Feb 10 2022)
AP opens and I can connect. The video stream is available but no HTML at 192.168.4.1
Message from AP: File does not exist or cannot be opened

**Comment by pgodd** [comment]
No log file is present on the SD, but several motion capture MJPEG files are stored.

**Comment by pgodd** [comment]
No I did not. Somehow missed that step.

**Comment by s60sc** [comment]
Thanks, amended readme to indicate instructable is not up to date

**Comment by pgodd** [comment]
That’s cool.
May I ask?
Do you think it is possible to set these cameras up as a daisy chain? I have an application in mind to deploy them as a network of trail cameras to cover about 3 acres of land.
P

**Comment by pgodd** [comment]
After asking I looked into it a bit and found Expressif has already posted a lot of info on setting up a mesh network. 
Now the question is do we have the overhead?
I’ll try and figure it out.
Thanks again.
