### ISSUE TITLE
audio sync

### ISSUE THREAD

**Issue by fotolexa2022** [s60sc/ESP32-CAM_MJPEG2SD#68]
Good evening!
When creating an .avi file on FTP, the audio sequence is 2 times shorter than the video sequence in duration.
The vav file that is created on the SD card also has 2 times less duration.

**Comment by s60sc** [comment]
Disparity between camera recording and playback rate but dont know why. An unknown change was made to the camera library that significantly impacted performance when both I2S channels are being used.

BTW what sort of audio quality did you get.
