### ISSUE TITLE
Whitespace removed in config

### ISSUE THREAD

**Issue by ludvigaldrin** [s60sc/ESP32-CAM_MJPEG2SD#69]
I have a Wifi SSID that has a white space in it. It is removed when loaded. I have hardcoded it in prefs.cpp for now to get around it. Maybe its a quick fix?

**Comment by ludvigaldrin** [comment]
And also any special Chars like # is removed :(

**Comment by s60sc** [comment]
As designed to prevent inadvertent whitespace in user entries.
Special chars are not deliberately removed

**Comment by ludvigaldrin** [comment]
Hmm, cant you use Trim for start and end? Im no C expert so dont know whats there.

**Comment by s60sc** [comment]
In the next build I'll include a define that will let you disable whitespace removal if wanted

**Comment by s60sc** [comment]
ALLOW_SPACES added
