### ISSUE TITLE
Time Laps File is empty

### ISSUE THREAD

**Issue by jotra-bischau** [s60sc/ESP32-CAM_MJPEG2SD#73]
Hello s60sc,
first of all I want to tell you that this is a very nice work. 
Thank you very much for it.
I have problems to record time Lapse Files. After activating the button in the web interface I can see in the Serial log-file:
_17:20:39.335 -> [17:20:39.673 timeLapse] Started time lapse file /20220320/20220320_172039_VGA_1_720_72_T.avi, interval 12000, for 72 frames_
But some time of capturing, when I will download the File, I found that this is empty. (Size 0.0MB)

**Comment by s60sc** [comment]
Thanks
Updated code so that time lapse file only created when time lapse completed

**Comment by jotra-bischau** [comment]
ok, 
thanks it works fine
