### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by jeonhaeng** [s60sc/ESP32-CAM_MJPEG2SD#77]
Thank you for good resource, it is vey helpful to me.

There is some trouble for me to apply this code.

How to reduce compile size.
I have error of oversize (108%) for ESP32 Wrover Module
   dynamic : 91416(27%) used, local variable 236264 left, max 327686 bytes

**Comment by s60sc** [comment]
See installation notes for partition scheme to use

**Comment by jeonhaeng** [comment]
> See installation notes for partition scheme to use

I fix my problem by your reply...
thx
