### ISSUE TITLE
Some recorded videos couldn't playback

### ISSUE THREAD

**Issue by kidboygmail** [s60sc/ESP32-CAM_MJPEG2SD#78]
Hi there,

Just found this amazing project and tried with latest code.
I'm not sure whether I'm the only one to meet this issue.

With default settings, only change the Resolution, then click "Record".
    Videos in HVGA and above can't playback with Windows Media Player or Movie&TV.
    Videos in QVGA and lower resolution work well.

Thank you!

**Comment by s60sc** [comment]
I use [VLC](https://www.videolan.org/)
