### ISSUE TITLE
ping/ping_sock.h: No such file or directory

### ISSUE THREAD

**Issue by Buttosaii** [s60sc/ESP32-CAM_MJPEG2SD#79]
Hi, i have git cloned this repo to my folder and it seems that i didn't need to remove the "master" as there wasn't any in the name. When i tried to upload the code, i was faced with this error:

myConfig.h:126:28: fatal error: ping/ping_sock.h: No such file or directory
compilation terminated.
exit status 1
ping/ping_sock.h: No such file or directory

Am i missing anything here?

**Comment by nnjim** [comment]
Have a look at issue 72:

https://github.com/s60sc/ESP32-CAM_MJPEG2SD/issues/72

**Comment by Buttosaii** [comment]
Thank you so much to all for your swift response, I have manage to solve it too but updating the board!
