### ISSUE TITLE
ESP32-CAM V6.2 Time Error

### ISSUE THREAD

**Issue by kondorcl** [s60sc/ESP32-CAM_MJPEG2SD#82]
Sir, please could you help me with wrong time display.

syncToBrowser] Sync clock to: 2022-04-11T19:14:56.791Z with tz:EST3EDT,M4.1.0/-4,M9.1.0/-3 this is ok

Camera Local Time : 2022-04-11 20:15:07 and this wrong.

Thanks,

**Comment by gemi254** [comment]
Synchronizing camera time to your browser time.
Check your browser time zone and camera time zone.
What is the timezone selected in camera interface?
is this timezone: EST3EDT,M4.1.0/-4,M9.1.0/-3 correct ?

As an example..

America/Sao_Paulo                                  Zone     EST3EDT,M10.3.0/00:00:00,M2.3.0/00:00:00

"M10.3.0/00:00:00" indicates: 
M10 is 10th month (October)
.3 is the third occurrence of the day in the month (in this example, the 3rd Sunday)
.0 is Sunday 
00:00:00 is the time, (12:00 am)

**Comment by gemi254** [comment]
Yes the `Time zone select` drop list is just a timezone selector to `Time zone` edit box..
Your browser/pc has a correct time / timezone ?

**Comment by kondorcl** [comment]
Yes sir.
![zhoraria](https://user-images.githubusercontent.com/7191927/163226772-621680fa-7080-40c7-b258-cf35a9cab401.png)
Uncomment lines 221 and 223 in utils.cpp

time_t t_of_day = mktime(&t);
  timeval epoch = {t_of_day, 0};
  struct timezone utc = {0, 0};
  settimeofday(&epoch, &utc);
  //setenv("TZ", timezone, 1);
  Serial.print(&now, "Before sync: %B %d %Y %H:%M:%S (%A) "); line 221
  getLocalTime(&now, 0);
  Serial.println(&now, "After sync: %B %d %Y %H:%M:%S (%A)"); line 223
  timeSynchronized = true;

and get this...

[21:00:04.374 WARN getLocalNTP] Not yet synced with NTP
[21:00:04.999 syncToBrowser] Sync clock to: 2022-04-13T12:24:14.869Z with tz:EST3EDT,M4.1.0/-4,M9.1.0/-3
Before sync: December 31 1969 21:00:05 (Wednesday) After sync: April 13 2022 12:24:14 (Wednesday) This is ok....
[13:24:48.363 fileHandler] Sent /data/MJPEG2SD.htm to browser
[13:24:49.136 fileHandler] Sent /data/jquery.min.js to browser

webdisplay: 1 hour early.
![time_webdisplay](https://user-images.githubusercontent.com/7191927/163227894-31de7fc8-33db-445a-b505-a62573914510.png)

The recorded time stamp is fine.

[13:29:04.517 closeAvi] ******** AVI recording stats ********
[13:29:04.518 closeAvi] Recorded /20220413/20220413_132651_VGA_20_133_2658.avi

Thanks.

**Comment by kondorcl** [comment]
Sir the problem was solved with this:
![clocksync](https://user-images.githubusercontent.com/7191927/163270103-7946b7c6-063e-4d6c-9297-285cf14960fb.png)

Thank very much..
