### ISSUE TITLE
It is not an issue it is a question Sleep mode

### ISSUE THREAD

**Issue by llamas112** [s60sc/ESP32-CAM_MJPEG2SD#88]
Hello I am using only the PIR sensor for motion capture (Pin 12) and I am trying to put the camera into Deep sleep mode when a recording is saved (almost got it),  but then i want to wake up the camera using the PIR sensor whe it detectcts movement (I cant do it). ¿Is it possible? or I am wasting the time. Thanks.

**Comment by llamas112** [comment]
I got it, but I can not find the best place to send the camera to sleep mode.
I've put it in several places, removing various pieces of code, so it is not the best thing.
I left the suggestion, in case anyone wants to tryit, I don't know what is the last thing that is read after finishing the recording to put the sleep there.

**Comment by s60sc** [comment]
I may look into adding a deep sleep mode when I have time

**Comment by s60sc** [comment]
After testing, waking up from deep sleep takes far too long

**Comment by llamas112** [comment]
OK, thanks for trying it, i didn't notice that when i tested
