### ISSUE TITLE
Email alerts not working

### ISSUE THREAD

**Issue by rernars** [s60sc/ESP32-CAM_MJPEG2SD#89]
While uploading the code from arduino ide i didn't switch the alerts on, but now i want to switch it on and there is no option in config to switch it on. I thought maybe if i just place my smtp info it will switch itself on but nope still it says email alerts not active. How can i switch it on?

**Comment by rernars** [comment]
And I have one more question (didn't want to bother with opening another issue since its a simple question) ; I wonder what kind of files i can upload with the OTA function and what purpose do the serve? Like can i upload a new config.h ( for example to turn email alerts on) ?

**Comment by s60sc** [comment]
In my config.h, set below to true and recompile
#define USE_SMTP false // whether or not to send email alerts

ota: any files used by app can be uploaded

**Comment by rernars** [comment]
So, can I just upload the new config.h from OTA ? It would be really difficult for me to update the config.h since i desoldered all pins from the esp32cam

**Comment by s60sc** [comment]
Yes

**Comment by rernars** [comment]
well, it didnt work. 
![image](https://user-images.githubusercontent.com/59098807/167076065-f194395e-535f-416b-918e-432e4be9e2bb.png)

**Comment by rernars** [comment]
![image](https://user-images.githubusercontent.com/59098807/178254842-d19067f1-8f4c-4974-a130-69214ec8fc10.png)
Well it didn't work as well , sorry for late reply
