### ISSUE TITLE
http-request - still image

### ISSUE THREAD

**Issue by elektroluki** [s60sc/ESP32-CAM_MJPEG2SD#90]
Hello! Great work with this software - very impressive!

Is is possible to fetch a still image by using an http request like
`wget -O thisCapture.jpg http://192.168.1.15/capture
`
In similar looking software ([ESP32CamTimeLapse](https://github.com/bitluni/ESP32CamTimeLapse/tree/master/TimeLapse)) this is possible, but I have trouble finding the functionality in this code.

Would appreciate a tip and thanks again for the great work!
  Lukas

**Comment by s60sc** [comment]
Thanks
answer is no, but you could look at this [fork](https://github.com/gemi254/ESP32-CAM_MJPEG2SD)
