### ISSUE TITLE
Question on adding logo

### ISSUE THREAD

**Issue by C4PT41ND34DP00L** [s60sc/ESP32-CAM_MJPEG2SD#99]
I tried adding an image as a logo on the web page with HTML. The image is kept in the data folder. If I just open the HTML page from the file it works without issue but when running the camera the logo does not show. I was curious if there was a structure I needed to use for when the web server is running to get this to work?

**Comment by s60sc** [comment]
The image href would need to be something like '/web?logo.jpg' to be recognised by the web server in webServer.cpp
